/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package interfaz;

import java.awt.BorderLayout;
import javax.swing.JPanel;
import juegos.Juego;
import niveles.Nivel;
import cronometros.Cronometro;
import javax.swing.Timer;

/**
 *
 * @author andre
 */
public class frmJuego extends javax.swing.JFrame {

    private Cronometro cronometro;
    private Timer actualizar;

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(frmJuego.class.getName());
    private Juego juego;
    private Nivel nivelActual;

    /* Creates new form frmJuego
     * @param nivel
     */
    public frmJuego(Nivel nivel) {
        initComponents();
        jpnPantalla.setLayout(new BorderLayout());

        cronometro = new Cronometro();
        cronometro.iniciar();

        actualizar = new Timer(1000, e -> {
            lblTimer.setText(cronometro.getTiempo_reiniciado());
        });

        actualizar.start();

        lblTimer.setText("0:00");

        this.nivelActual = nivel;
        juego = new Juego(nivel);
        
        lblScore.setText("Puntaje: " + juego.getJugador().getScore());
        lblIntentos.setText("Intentos: " + juego.getJugador().getAttempts());

        JPanel panel;
        switch (nivel.getParejas()) {
            case 8 ->
                panel = new jpnFacil(this.juego);
            case 16 ->
                panel = new jpnIntermedio(this.juego);
            case 32 ->
                panel = new jpnAvanzado(this.juego);
            default ->
                panel = new JPanel(this.juego);
        }
        mostrarJuego(panel);

    }

    private void mostrarJuego(JPanel panel) {
        jpnPantalla.removeAll();
        jpnPantalla.add(panel, BorderLayout.CENTER);
        jpnPantalla.revalidate();
        jpnPantalla.repaint();
        this.setTitle("Juego de memoria - " + nivelActual);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jpnPantalla = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jpnInfo = new javax.swing.JPanel();
        lblTimer = new javax.swing.JLabel();
        btnMenu = new javax.swing.JButton();
        btnReiniciar = new javax.swing.JButton();
        lblScore = new javax.swing.JLabel();
        lblIntentos = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jpnPantalla.setBorder(new javax.swing.border.MatteBorder(null));

        jLabel1.setText("jLabel1");

        javax.swing.GroupLayout jpnPantallaLayout = new javax.swing.GroupLayout(jpnPantalla);
        jpnPantalla.setLayout(jpnPantallaLayout);
        jpnPantallaLayout.setHorizontalGroup(
            jpnPantallaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnPantallaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addContainerGap(465, Short.MAX_VALUE))
        );
        jpnPantallaLayout.setVerticalGroup(
            jpnPantallaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnPantallaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addContainerGap(566, Short.MAX_VALUE))
        );

        getContentPane().add(jpnPantalla, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jpnInfo.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        lblTimer.setText("lblTimer");

        btnMenu.setText("Menu");
        btnMenu.addActionListener(this::btnMenuActionPerformed);

        btnReiniciar.setText("Reiniciar");
        btnReiniciar.addActionListener(this::btnReiniciarActionPerformed);

        lblScore.setText("lblScore");

        lblIntentos.setText("lblIntentos");

        javax.swing.GroupLayout jpnInfoLayout = new javax.swing.GroupLayout(jpnInfo);
        jpnInfo.setLayout(jpnInfoLayout);
        jpnInfoLayout.setHorizontalGroup(
            jpnInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpnInfoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnMenu)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnReiniciar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 189, Short.MAX_VALUE)
                .addComponent(lblScore)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblIntentos)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblTimer)
                .addContainerGap())
        );
        jpnInfoLayout.setVerticalGroup(
            jpnInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnInfoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpnInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTimer)
                    .addComponent(btnMenu)
                    .addComponent(btnReiniciar)
                    .addComponent(lblScore)
                    .addComponent(lblIntentos))
                .addContainerGap(9, Short.MAX_VALUE))
        );

        getContentPane().add(jpnInfo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 590, 510, 40));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMenuActionPerformed
        actualizar.stop();
        cronometro.detener();
        frmMenu menu = new frmMenu();
        menu.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnMenuActionPerformed

    private void btnReiniciarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReiniciarActionPerformed

        cronometro.reiniciar();

        lblTimer.setText("0:00");

        if (!actualizar.isRunning()) {
            actualizar.start();
        }
    }//GEN-LAST:event_btnReiniciarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        Nivel nivel;

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new frmJuego(Nivel.PRINCIPIANTE).setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnMenu;
    private javax.swing.JButton btnReiniciar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jpnInfo;
    private javax.swing.JPanel jpnPantalla;
    private javax.swing.JLabel lblIntentos;
    private javax.swing.JLabel lblScore;
    private javax.swing.JLabel lblTimer;
    // End of variables declaration//GEN-END:variables
}
