/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package interfaz;

/**
 *
 * @author andre
 */
public class frmMenu extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(frmMenu.class.getName());
        private frmJuego juego;
    /**
     * Creates new form frmMenu
     */
    public frmMenu() {
        initComponents();
        juego = new frmJuego();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnPrincipiante = new javax.swing.JButton();
        btnIntermedio = new javax.swing.JButton();
        btnAvanzado = new javax.swing.JButton();
        lblDificultad = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnPrincipiante.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnPrincipiante.setText("Principiante");
        btnPrincipiante.setVerticalTextPosition(javax.swing.SwingConstants.TOP);
        btnPrincipiante.addActionListener(this::btnPrincipianteActionPerformed);

        btnIntermedio.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnIntermedio.setText("Intermedio");
        btnIntermedio.setVerticalTextPosition(javax.swing.SwingConstants.TOP);

        btnAvanzado.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnAvanzado.setText("Avanzado");
        btnAvanzado.setVerticalTextPosition(javax.swing.SwingConstants.TOP);
        btnAvanzado.addActionListener(this::btnAvanzadoActionPerformed);

        lblDificultad.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lblDificultad.setText("Dificultad");
        lblDificultad.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(356, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnAvanzado, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnIntermedio, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnPrincipiante, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(356, 356, 356))
            .addGroup(layout.createSequentialGroup()
                .addGap(418, 418, 418)
                .addComponent(lblDificultad)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(220, 220, 220)
                .addComponent(lblDificultad)
                .addGap(18, 18, 18)
                .addComponent(btnPrincipiante)
                .addGap(18, 18, 18)
                .addComponent(btnIntermedio)
                .addGap(18, 18, 18)
                .addComponent(btnAvanzado)
                .addContainerGap(222, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnPrincipianteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPrincipianteActionPerformed
        juego.
    }//GEN-LAST:event_btnPrincipianteActionPerformed

    private void btnAvanzadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAvanzadoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnAvanzadoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new frmMenu().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAvanzado;
    private javax.swing.JButton btnIntermedio;
    private javax.swing.JButton btnPrincipiante;
    private javax.swing.JLabel lblDificultad;
    // End of variables declaration//GEN-END:variables
}
