/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package interfaz;

import niveles.Nivel;

/**
 *
 * @author andre
 */
public class frmMenu extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(frmMenu.class.getName());
    /**
     * Creates new form frmMenu
     */
    public frmMenu() {
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        txtNivel = new javax.swing.JComboBox<>();
        lblDificultad = new javax.swing.JLabel();
        btnIniciar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtNivel.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        txtNivel.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Principiante", "Intermedio", "Avanzado", " " }));
        jPanel1.add(txtNivel, new org.netbeans.lib.awtextra.AbsoluteConstraints(143, 211, 227, -1));

        lblDificultad.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        lblDificultad.setText("Dificultad");
        lblDificultad.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanel1.add(lblDificultad, new org.netbeans.lib.awtextra.AbsoluteConstraints(179, 145, -1, -1));

        btnIniciar.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnIniciar.setText("Iniciar Juego");
        btnIniciar.addActionListener(this::btnIniciarActionPerformed);
        jPanel1.add(btnIniciar, new org.netbeans.lib.awtextra.AbsoluteConstraints(143, 313, 227, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 510, 630));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnIniciarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIniciarActionPerformed
        int opc = txtNivel.getSelectedIndex();
        Nivel nivel = null;
        switch(opc){
            case 0 -> {
                nivel= Nivel.PRINCIPIANTE;
            }
            case 1 ->{
                nivel= Nivel.INTERMEDIO;
            }
            case 2 ->{
                nivel = Nivel.AVANZADO;
            }
        }
        frmJuego juego = new frmJuego(nivel);
        juego.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnIniciarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new frmMenu().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnIniciar;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblDificultad;
    private javax.swing.JComboBox<String> txtNivel;
    // End of variables declaration//GEN-END:variables
}
