/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package interfaz;

import javax.swing.JButton;
import juegos.Juego;

/**
 *
 * @author lenno
 */
public class jpnAvanzado extends javax.swing.JPanel {
    private Juego juego;
JButton[] botones = new JButton [64];
    /**
     * Creates new form jpnAvanzado
     */
    public jpnAvanzado(Juego juego) {
        
        initComponents();
        this.juego = juego;
        
botones[0] = btnf1c1;
botones[1] = btnf1c2;
botones[2] = btnf1c3;
botones[3] = btnf1c4;
botones[4] = btnf1c5;
botones[5] = btnf1c6;
botones[6] = btnf1c7;
botones[7] = btnf1c8;
botones[8] = btnf2c1;
botones[9] = btnf2c2;
botones[10] = btnf2c3;
botones[11] = btnf2c4;
botones[12] = btnf2c5;
botones[13] = btnf2c6;
botones[14] = btnf2c7;
botones[15] = btnf2c8;
botones[16] = btnf3c1;
botones[17] = btnf3c2;
botones[18] = btnf3c3;
botones[19] = btnf3c4;
botones[20] = btnf3c5;
botones[21] = btnf3c6;
botones[22] = btnf3c7;
botones[23] = btnf3c8;
botones[24] = btnf4c1;
botones[25] = btnf4c2;
botones[26] = btnf4c3;
botones[27] = btnf4c4;
botones[28] = btnf4c5;
botones[29] = btnf4c6;
botones[30] = btnf4c7;
botones[31] = btnf4c8;
botones[32] = btnf5c1;
botones[33] = btnf5c2;
botones[34] = btnf5c3;
botones[35] = btnf5c4;
botones[36] = btnf5c5;
botones[37] = btnf5c6;
botones[38] = btnf5c7;
botones[39] = btnf5c8;
botones[40] = btnf6c1;
botones[41] = btnf6c2;
botones[42] = btnf6c3;
botones[43] = btnf6c4;
botones[44] = btnf6c5;
botones[45] = btnf6c6;
botones[46] = btnf6c7;
botones[47] = btnf6c8;
botones[48] = btnf7c1;
botones[49] = btnf7c2;
botones[50] = btnf7c3;
botones[51] = btnf7c4;
botones[52] = btnf7c5;
botones[53] = btnf7c6;
botones[54] = btnf7c7;
botones[55] = btnf7c8;
botones[56] = btnf8c1;
botones[57] = btnf8c2;
botones[58] = btnf8c3;
botones[59] = btnf8c4;
botones[60] = btnf8c5;
botones[61] = btnf8c6;
botones[62] = btnf8c7;
botones[63] = btnf8c8;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btnf1c7 = new javax.swing.JButton();
        btnf1c2 = new javax.swing.JButton();
        btnf1c5 = new javax.swing.JButton();
        btnf1c1 = new javax.swing.JButton();
        btnf1c3 = new javax.swing.JButton();
        btnf1c6 = new javax.swing.JButton();
        btnf1c4 = new javax.swing.JButton();
        btnf1c8 = new javax.swing.JButton();
        btnf2c4 = new javax.swing.JButton();
        btnf2c7 = new javax.swing.JButton();
        btnf2c2 = new javax.swing.JButton();
        btnf2c8 = new javax.swing.JButton();
        btnf2c5 = new javax.swing.JButton();
        btnf2c1 = new javax.swing.JButton();
        btnf2c3 = new javax.swing.JButton();
        btnf2c6 = new javax.swing.JButton();
        btnf3c4 = new javax.swing.JButton();
        btnf3c7 = new javax.swing.JButton();
        btnf3c2 = new javax.swing.JButton();
        btnf3c8 = new javax.swing.JButton();
        btnf3c5 = new javax.swing.JButton();
        btnf3c1 = new javax.swing.JButton();
        btnf4c4 = new javax.swing.JButton();
        btnf3c3 = new javax.swing.JButton();
        btnf4c7 = new javax.swing.JButton();
        btnf4c2 = new javax.swing.JButton();
        btnf4c8 = new javax.swing.JButton();
        btnf4c5 = new javax.swing.JButton();
        btnf4c1 = new javax.swing.JButton();
        btnf4c3 = new javax.swing.JButton();
        btnf4c6 = new javax.swing.JButton();
        btnf3c6 = new javax.swing.JButton();
        btnf7c2 = new javax.swing.JButton();
        btnf7c8 = new javax.swing.JButton();
        btnf7c5 = new javax.swing.JButton();
        btnf7c1 = new javax.swing.JButton();
        btnf8c4 = new javax.swing.JButton();
        btnf7c3 = new javax.swing.JButton();
        btnf5c4 = new javax.swing.JButton();
        btnf8c7 = new javax.swing.JButton();
        btnf8c2 = new javax.swing.JButton();
        btnf8c8 = new javax.swing.JButton();
        btnf5c7 = new javax.swing.JButton();
        btnf5c2 = new javax.swing.JButton();
        btnf5c8 = new javax.swing.JButton();
        btnf5c5 = new javax.swing.JButton();
        btnf5c1 = new javax.swing.JButton();
        btnf6c4 = new javax.swing.JButton();
        btnf5c3 = new javax.swing.JButton();
        btnf8c5 = new javax.swing.JButton();
        btnf8c1 = new javax.swing.JButton();
        btnf6c7 = new javax.swing.JButton();
        btnf8c3 = new javax.swing.JButton();
        btnf6c2 = new javax.swing.JButton();
        btnf8c6 = new javax.swing.JButton();
        btnf6c8 = new javax.swing.JButton();
        btnf7c6 = new javax.swing.JButton();
        btnf6c5 = new javax.swing.JButton();
        btnf6c1 = new javax.swing.JButton();
        btnf6c3 = new javax.swing.JButton();
        btnf6c6 = new javax.swing.JButton();
        btnf7c4 = new javax.swing.JButton();
        btnf7c7 = new javax.swing.JButton();
        btnf5c6 = new javax.swing.JButton();

        jPanel1.setPreferredSize(new java.awt.Dimension(510, 590));

        btnf1c7.setMaximumSize(new java.awt.Dimension(63, 5));
        btnf1c7.setMinimumSize(new java.awt.Dimension(63, 5));

        btnf1c2.setMaximumSize(new java.awt.Dimension(63, 5));
        btnf1c2.setMinimumSize(new java.awt.Dimension(63, 5));
        btnf1c2.addActionListener(this::btnf1c2ActionPerformed);

        btnf1c5.setMaximumSize(new java.awt.Dimension(63, 5));
        btnf1c5.setMinimumSize(new java.awt.Dimension(63, 5));

        btnf1c1.setMaximumSize(new java.awt.Dimension(63, 5));
        btnf1c1.setMinimumSize(new java.awt.Dimension(63, 5));

        btnf1c3.setMaximumSize(new java.awt.Dimension(63, 5));
        btnf1c3.setMinimumSize(new java.awt.Dimension(63, 5));

        btnf1c6.setMaximumSize(new java.awt.Dimension(63, 5));
        btnf1c6.setMinimumSize(new java.awt.Dimension(63, 5));

        btnf1c4.setMaximumSize(new java.awt.Dimension(63, 5));
        btnf1c4.setMinimumSize(new java.awt.Dimension(63, 5));
        btnf1c4.addActionListener(this::btnf1c4ActionPerformed);

        btnf1c8.setMaximumSize(new java.awt.Dimension(63, 5));
        btnf1c8.setMinimumSize(new java.awt.Dimension(63, 5));

        btnf2c4.setMaximumSize(new java.awt.Dimension(63, 5));
        btnf2c4.setMinimumSize(new java.awt.Dimension(63, 5));

        btnf2c7.setMaximumSize(new java.awt.Dimension(63, 5));
        btnf2c7.setMinimumSize(new java.awt.Dimension(63, 5));

        btnf2c2.setMaximumSize(new java.awt.Dimension(63, 5));
        btnf2c2.setMinimumSize(new java.awt.Dimension(63, 5));
        btnf2c2.addActionListener(this::btnf2c2ActionPerformed);

        btnf2c8.setMaximumSize(new java.awt.Dimension(63, 5));
        btnf2c8.setMinimumSize(new java.awt.Dimension(63, 5));

        btnf2c5.setMaximumSize(new java.awt.Dimension(63, 5));
        btnf2c5.setMinimumSize(new java.awt.Dimension(63, 5));

        btnf2c1.setMaximumSize(new java.awt.Dimension(63, 5));
        btnf2c1.setMinimumSize(new java.awt.Dimension(63, 5));

        btnf2c3.setMaximumSize(new java.awt.Dimension(63, 5));
        btnf2c3.setMinimumSize(new java.awt.Dimension(63, 5));

        btnf2c6.setMaximumSize(new java.awt.Dimension(63, 5));
        btnf2c6.setMinimumSize(new java.awt.Dimension(63, 5));

        btnf3c4.setMaximumSize(new java.awt.Dimension(63, 5));
        btnf3c4.setMinimumSize(new java.awt.Dimension(63, 5));

        btnf3c7.setMaximumSize(new java.awt.Dimension(63, 5));
        btnf3c7.setMinimumSize(new java.awt.Dimension(63, 5));

        btnf3c2.setMaximumSize(new java.awt.Dimension(63, 5));
        btnf3c2.setMinimumSize(new java.awt.Dimension(63, 5));
        btnf3c2.addActionListener(this::btnf3c2ActionPerformed);

        btnf3c8.setMaximumSize(new java.awt.Dimension(63, 5));
        btnf3c8.setMinimumSize(new java.awt.Dimension(63, 5));

        btnf3c5.setMaximumSize(new java.awt.Dimension(63, 5));
        btnf3c5.setMinimumSize(new java.awt.Dimension(63, 5));

        btnf3c1.setMaximumSize(new java.awt.Dimension(63, 5));
        btnf3c1.setMinimumSize(new java.awt.Dimension(63, 5));

        btnf4c4.setMaximumSize(new java.awt.Dimension(63, 5));
        btnf4c4.setMinimumSize(new java.awt.Dimension(63, 5));

        btnf3c3.setMaximumSize(new java.awt.Dimension(63, 5));
        btnf3c3.setMinimumSize(new java.awt.Dimension(63, 5));

        btnf4c7.setMaximumSize(new java.awt.Dimension(63, 5));
        btnf4c7.setMinimumSize(new java.awt.Dimension(63, 5));

        btnf4c2.setMaximumSize(new java.awt.Dimension(63, 5));
        btnf4c2.setMinimumSize(new java.awt.Dimension(63, 5));
        btnf4c2.addActionListener(this::btnf4c2ActionPerformed);

        btnf4c8.setMaximumSize(new java.awt.Dimension(63, 5));
        btnf4c8.setMinimumSize(new java.awt.Dimension(63, 5));

        btnf4c5.setMaximumSize(new java.awt.Dimension(63, 5));
        btnf4c5.setMinimumSize(new java.awt.Dimension(63, 5));

        btnf4c1.setMaximumSize(new java.awt.Dimension(63, 5));
        btnf4c1.setMinimumSize(new java.awt.Dimension(63, 5));

        btnf4c3.setMaximumSize(new java.awt.Dimension(63, 5));
        btnf4c3.setMinimumSize(new java.awt.Dimension(63, 5));

        btnf4c6.setMaximumSize(new java.awt.Dimension(63, 5));
        btnf4c6.setMinimumSize(new java.awt.Dimension(63, 5));

        btnf3c6.setMaximumSize(new java.awt.Dimension(63, 5));
        btnf3c6.setMinimumSize(new java.awt.Dimension(63, 5));

        btnf7c2.setMaximumSize(new java.awt.Dimension(63, 5));
        btnf7c2.setMinimumSize(new java.awt.Dimension(63, 5));
        btnf7c2.addActionListener(this::btnf7c2ActionPerformed);

        btnf7c8.setMaximumSize(new java.awt.Dimension(63, 5));
        btnf7c8.setMinimumSize(new java.awt.Dimension(63, 5));

        btnf7c5.setMaximumSize(new java.awt.Dimension(63, 5));
        btnf7c5.setMinimumSize(new java.awt.Dimension(63, 5));

        btnf7c1.setMaximumSize(new java.awt.Dimension(63, 5));
        btnf7c1.setMinimumSize(new java.awt.Dimension(63, 5));

        btnf8c4.setMaximumSize(new java.awt.Dimension(63, 5));
        btnf8c4.setMinimumSize(new java.awt.Dimension(63, 5));

        btnf7c3.setMaximumSize(new java.awt.Dimension(63, 5));
        btnf7c3.setMinimumSize(new java.awt.Dimension(63, 5));

        btnf5c4.setMaximumSize(new java.awt.Dimension(63, 5));
        btnf5c4.setMinimumSize(new java.awt.Dimension(63, 5));

        btnf8c7.setMaximumSize(new java.awt.Dimension(63, 5));
        btnf8c7.setMinimumSize(new java.awt.Dimension(63, 5));

        btnf8c2.setMaximumSize(new java.awt.Dimension(63, 5));
        btnf8c2.setMinimumSize(new java.awt.Dimension(63, 5));
        btnf8c2.addActionListener(this::btnf8c2ActionPerformed);

        btnf8c8.setMaximumSize(new java.awt.Dimension(63, 5));
        btnf8c8.setMinimumSize(new java.awt.Dimension(63, 5));

        btnf5c7.setMaximumSize(new java.awt.Dimension(63, 5));
        btnf5c7.setMinimumSize(new java.awt.Dimension(63, 5));

        btnf5c2.setMaximumSize(new java.awt.Dimension(63, 5));
        btnf5c2.setMinimumSize(new java.awt.Dimension(63, 5));
        btnf5c2.addActionListener(this::btnf5c2ActionPerformed);

        btnf5c8.setMaximumSize(new java.awt.Dimension(63, 5));
        btnf5c8.setMinimumSize(new java.awt.Dimension(63, 5));

        btnf5c5.setMaximumSize(new java.awt.Dimension(63, 5));
        btnf5c5.setMinimumSize(new java.awt.Dimension(63, 5));

        btnf5c1.setMaximumSize(new java.awt.Dimension(63, 5));
        btnf5c1.setMinimumSize(new java.awt.Dimension(63, 5));

        btnf6c4.setMaximumSize(new java.awt.Dimension(63, 5));
        btnf6c4.setMinimumSize(new java.awt.Dimension(63, 5));

        btnf5c3.setMaximumSize(new java.awt.Dimension(63, 5));
        btnf5c3.setMinimumSize(new java.awt.Dimension(63, 5));

        btnf8c5.setMaximumSize(new java.awt.Dimension(63, 5));
        btnf8c5.setMinimumSize(new java.awt.Dimension(63, 5));

        btnf8c1.setMaximumSize(new java.awt.Dimension(63, 5));
        btnf8c1.setMinimumSize(new java.awt.Dimension(63, 5));

        btnf6c7.setMaximumSize(new java.awt.Dimension(63, 5));
        btnf6c7.setMinimumSize(new java.awt.Dimension(63, 5));

        btnf8c3.setMaximumSize(new java.awt.Dimension(63, 5));
        btnf8c3.setMinimumSize(new java.awt.Dimension(63, 5));

        btnf6c2.setMaximumSize(new java.awt.Dimension(63, 5));
        btnf6c2.setMinimumSize(new java.awt.Dimension(63, 5));
        btnf6c2.addActionListener(this::btnf6c2ActionPerformed);

        btnf8c6.setMaximumSize(new java.awt.Dimension(63, 5));
        btnf8c6.setMinimumSize(new java.awt.Dimension(63, 5));

        btnf6c8.setMaximumSize(new java.awt.Dimension(63, 5));
        btnf6c8.setMinimumSize(new java.awt.Dimension(63, 5));

        btnf7c6.setMaximumSize(new java.awt.Dimension(63, 5));
        btnf7c6.setMinimumSize(new java.awt.Dimension(63, 5));

        btnf6c5.setMaximumSize(new java.awt.Dimension(63, 5));
        btnf6c5.setMinimumSize(new java.awt.Dimension(63, 5));

        btnf6c1.setMaximumSize(new java.awt.Dimension(63, 5));
        btnf6c1.setMinimumSize(new java.awt.Dimension(63, 5));

        btnf6c3.setMaximumSize(new java.awt.Dimension(63, 5));
        btnf6c3.setMinimumSize(new java.awt.Dimension(63, 5));

        btnf6c6.setMaximumSize(new java.awt.Dimension(63, 5));
        btnf6c6.setMinimumSize(new java.awt.Dimension(63, 5));

        btnf7c4.setMaximumSize(new java.awt.Dimension(63, 5));
        btnf7c4.setMinimumSize(new java.awt.Dimension(63, 5));

        btnf7c7.setMaximumSize(new java.awt.Dimension(63, 5));
        btnf7c7.setMinimumSize(new java.awt.Dimension(63, 5));

        btnf5c6.setMaximumSize(new java.awt.Dimension(63, 5));
        btnf5c6.setMinimumSize(new java.awt.Dimension(63, 5));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(35, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btnf1c1, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnf1c2, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnf1c3, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnf1c4, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnf1c5, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnf1c6, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnf1c7, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnf1c8, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btnf2c1, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnf2c2, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnf2c3, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnf2c4, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnf2c5, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnf2c6, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnf2c7, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnf2c8, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btnf3c1, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnf3c2, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnf3c3, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnf3c4, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnf3c5, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnf3c6, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnf3c7, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnf3c8, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btnf4c1, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnf4c2, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnf4c3, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnf4c4, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnf4c5, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnf4c6, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnf4c7, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnf4c8, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btnf5c1, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnf5c2, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnf5c3, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnf5c4, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnf5c5, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnf5c6, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnf5c7, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnf5c8, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btnf6c1, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnf6c2, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnf6c3, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnf6c4, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnf6c5, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnf6c6, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnf6c7, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnf6c8, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btnf7c1, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnf7c2, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnf7c3, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnf7c4, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnf7c5, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnf7c6, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnf7c7, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnf7c8, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btnf8c1, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnf8c2, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnf8c3, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnf8c4, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnf8c5, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnf8c6, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnf8c7, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnf8c8, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(29, 29, 29))
        );

        jPanel1Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {btnf1c1, btnf1c2, btnf1c3, btnf1c4, btnf1c5, btnf1c6, btnf1c7, btnf1c8, btnf2c1, btnf2c2, btnf2c3, btnf2c4, btnf2c5, btnf2c6, btnf2c7, btnf2c8, btnf3c1, btnf3c2, btnf3c3, btnf3c4, btnf3c5, btnf3c6, btnf3c7, btnf3c8, btnf4c1, btnf4c2, btnf4c3, btnf4c4, btnf4c5, btnf4c6, btnf4c7, btnf4c8, btnf5c1, btnf5c2, btnf5c3, btnf5c4, btnf5c5, btnf5c6, btnf5c7, btnf5c8, btnf6c1, btnf6c2, btnf6c3, btnf6c4, btnf6c5, btnf6c6, btnf6c7, btnf6c8, btnf7c1, btnf7c2, btnf7c3, btnf7c4, btnf7c5, btnf7c6, btnf7c7, btnf7c8, btnf8c1, btnf8c2, btnf8c3, btnf8c4, btnf8c5, btnf8c6, btnf8c7, btnf8c8});

        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(btnf1c1, javax.swing.GroupLayout.DEFAULT_SIZE, 67, Short.MAX_VALUE)
                        .addComponent(btnf1c3, javax.swing.GroupLayout.DEFAULT_SIZE, 67, Short.MAX_VALUE)
                        .addComponent(btnf1c4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 67, Short.MAX_VALUE)
                        .addComponent(btnf1c5, javax.swing.GroupLayout.DEFAULT_SIZE, 67, Short.MAX_VALUE)
                        .addComponent(btnf1c6, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 67, Short.MAX_VALUE)
                        .addComponent(btnf1c8, javax.swing.GroupLayout.DEFAULT_SIZE, 67, Short.MAX_VALUE)
                        .addComponent(btnf1c7, javax.swing.GroupLayout.DEFAULT_SIZE, 67, Short.MAX_VALUE))
                    .addComponent(btnf1c2, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(btnf2c1, javax.swing.GroupLayout.DEFAULT_SIZE, 67, Short.MAX_VALUE)
                        .addComponent(btnf2c3, javax.swing.GroupLayout.DEFAULT_SIZE, 67, Short.MAX_VALUE)
                        .addComponent(btnf2c4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 67, Short.MAX_VALUE)
                        .addComponent(btnf2c5, javax.swing.GroupLayout.DEFAULT_SIZE, 67, Short.MAX_VALUE)
                        .addComponent(btnf2c6, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 67, Short.MAX_VALUE)
                        .addComponent(btnf2c8, javax.swing.GroupLayout.DEFAULT_SIZE, 67, Short.MAX_VALUE)
                        .addComponent(btnf2c7, javax.swing.GroupLayout.DEFAULT_SIZE, 67, Short.MAX_VALUE))
                    .addComponent(btnf2c2, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(btnf3c1, javax.swing.GroupLayout.DEFAULT_SIZE, 67, Short.MAX_VALUE)
                        .addComponent(btnf3c3, javax.swing.GroupLayout.DEFAULT_SIZE, 67, Short.MAX_VALUE)
                        .addComponent(btnf3c4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 67, Short.MAX_VALUE)
                        .addComponent(btnf3c5, javax.swing.GroupLayout.DEFAULT_SIZE, 67, Short.MAX_VALUE)
                        .addComponent(btnf3c6, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 67, Short.MAX_VALUE)
                        .addComponent(btnf3c8, javax.swing.GroupLayout.DEFAULT_SIZE, 67, Short.MAX_VALUE)
                        .addComponent(btnf3c7, javax.swing.GroupLayout.DEFAULT_SIZE, 67, Short.MAX_VALUE))
                    .addComponent(btnf3c2, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(btnf4c1, javax.swing.GroupLayout.DEFAULT_SIZE, 67, Short.MAX_VALUE)
                        .addComponent(btnf4c3, javax.swing.GroupLayout.DEFAULT_SIZE, 67, Short.MAX_VALUE)
                        .addComponent(btnf4c4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 67, Short.MAX_VALUE)
                        .addComponent(btnf4c5, javax.swing.GroupLayout.DEFAULT_SIZE, 67, Short.MAX_VALUE)
                        .addComponent(btnf4c6, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 67, Short.MAX_VALUE)
                        .addComponent(btnf4c8, javax.swing.GroupLayout.DEFAULT_SIZE, 67, Short.MAX_VALUE)
                        .addComponent(btnf4c7, javax.swing.GroupLayout.DEFAULT_SIZE, 67, Short.MAX_VALUE))
                    .addComponent(btnf4c2, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(btnf5c1, javax.swing.GroupLayout.DEFAULT_SIZE, 67, Short.MAX_VALUE)
                        .addComponent(btnf5c3, javax.swing.GroupLayout.DEFAULT_SIZE, 67, Short.MAX_VALUE)
                        .addComponent(btnf5c4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 67, Short.MAX_VALUE)
                        .addComponent(btnf5c5, javax.swing.GroupLayout.DEFAULT_SIZE, 67, Short.MAX_VALUE)
                        .addComponent(btnf5c6, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 67, Short.MAX_VALUE)
                        .addComponent(btnf5c8, javax.swing.GroupLayout.DEFAULT_SIZE, 67, Short.MAX_VALUE)
                        .addComponent(btnf5c7, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btnf5c2, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(btnf6c1, javax.swing.GroupLayout.DEFAULT_SIZE, 67, Short.MAX_VALUE)
                        .addComponent(btnf6c3, javax.swing.GroupLayout.DEFAULT_SIZE, 67, Short.MAX_VALUE)
                        .addComponent(btnf6c4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 67, Short.MAX_VALUE)
                        .addComponent(btnf6c5, javax.swing.GroupLayout.DEFAULT_SIZE, 67, Short.MAX_VALUE)
                        .addComponent(btnf6c6, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 67, Short.MAX_VALUE)
                        .addComponent(btnf6c8, javax.swing.GroupLayout.DEFAULT_SIZE, 67, Short.MAX_VALUE)
                        .addComponent(btnf6c7, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btnf6c2, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(btnf7c1, javax.swing.GroupLayout.DEFAULT_SIZE, 67, Short.MAX_VALUE)
                        .addComponent(btnf7c3, javax.swing.GroupLayout.DEFAULT_SIZE, 67, Short.MAX_VALUE)
                        .addComponent(btnf7c4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 67, Short.MAX_VALUE)
                        .addComponent(btnf7c5, javax.swing.GroupLayout.DEFAULT_SIZE, 67, Short.MAX_VALUE)
                        .addComponent(btnf7c6, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 67, Short.MAX_VALUE)
                        .addComponent(btnf7c8, javax.swing.GroupLayout.DEFAULT_SIZE, 67, Short.MAX_VALUE)
                        .addComponent(btnf7c7, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btnf7c2, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(btnf8c1, javax.swing.GroupLayout.DEFAULT_SIZE, 67, Short.MAX_VALUE)
                        .addComponent(btnf8c3, javax.swing.GroupLayout.DEFAULT_SIZE, 67, Short.MAX_VALUE)
                        .addComponent(btnf8c4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 67, Short.MAX_VALUE)
                        .addComponent(btnf8c5, javax.swing.GroupLayout.DEFAULT_SIZE, 67, Short.MAX_VALUE)
                        .addComponent(btnf8c6, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 67, Short.MAX_VALUE)
                        .addComponent(btnf8c7, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnf8c8, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btnf8c2, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel1Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {btnf1c1, btnf1c2, btnf1c3, btnf1c4, btnf1c5, btnf1c6, btnf1c7, btnf1c8, btnf2c1, btnf2c2, btnf2c3, btnf2c4, btnf2c5, btnf2c6, btnf2c7, btnf2c8, btnf3c1, btnf3c2, btnf3c3, btnf3c4, btnf3c5, btnf3c6, btnf3c7, btnf3c8, btnf4c1, btnf4c2, btnf4c3, btnf4c4, btnf4c5, btnf4c6, btnf4c7, btnf4c8, btnf5c1, btnf5c2, btnf5c3, btnf5c4, btnf5c5, btnf5c6, btnf5c7, btnf5c8, btnf6c1, btnf6c2, btnf6c3, btnf6c4, btnf6c5, btnf6c6, btnf6c7, btnf6c8, btnf7c1, btnf7c2, btnf7c3, btnf7c4, btnf7c5, btnf7c6, btnf7c7, btnf7c8, btnf8c1, btnf8c2, btnf8c3, btnf8c4, btnf8c5, btnf8c6, btnf8c7, btnf8c8});

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 498, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnf1c2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnf1c2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnf1c2ActionPerformed

    private void btnf2c2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnf2c2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnf2c2ActionPerformed

    private void btnf3c2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnf3c2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnf3c2ActionPerformed

    private void btnf4c2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnf4c2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnf4c2ActionPerformed

    private void btnf7c2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnf7c2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnf7c2ActionPerformed

    private void btnf8c2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnf8c2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnf8c2ActionPerformed

    private void btnf5c2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnf5c2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnf5c2ActionPerformed

    private void btnf6c2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnf6c2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnf6c2ActionPerformed

    private void btnf1c4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnf1c4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnf1c4ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnf1c1;
    private javax.swing.JButton btnf1c2;
    private javax.swing.JButton btnf1c3;
    private javax.swing.JButton btnf1c4;
    private javax.swing.JButton btnf1c5;
    private javax.swing.JButton btnf1c6;
    private javax.swing.JButton btnf1c7;
    private javax.swing.JButton btnf1c8;
    private javax.swing.JButton btnf2c1;
    private javax.swing.JButton btnf2c2;
    private javax.swing.JButton btnf2c3;
    private javax.swing.JButton btnf2c4;
    private javax.swing.JButton btnf2c5;
    private javax.swing.JButton btnf2c6;
    private javax.swing.JButton btnf2c7;
    private javax.swing.JButton btnf2c8;
    private javax.swing.JButton btnf3c1;
    private javax.swing.JButton btnf3c2;
    private javax.swing.JButton btnf3c3;
    private javax.swing.JButton btnf3c4;
    private javax.swing.JButton btnf3c5;
    private javax.swing.JButton btnf3c6;
    private javax.swing.JButton btnf3c7;
    private javax.swing.JButton btnf3c8;
    private javax.swing.JButton btnf4c1;
    private javax.swing.JButton btnf4c2;
    private javax.swing.JButton btnf4c3;
    private javax.swing.JButton btnf4c4;
    private javax.swing.JButton btnf4c5;
    private javax.swing.JButton btnf4c6;
    private javax.swing.JButton btnf4c7;
    private javax.swing.JButton btnf4c8;
    private javax.swing.JButton btnf5c1;
    private javax.swing.JButton btnf5c2;
    private javax.swing.JButton btnf5c3;
    private javax.swing.JButton btnf5c4;
    private javax.swing.JButton btnf5c5;
    private javax.swing.JButton btnf5c6;
    private javax.swing.JButton btnf5c7;
    private javax.swing.JButton btnf5c8;
    private javax.swing.JButton btnf6c1;
    private javax.swing.JButton btnf6c2;
    private javax.swing.JButton btnf6c3;
    private javax.swing.JButton btnf6c4;
    private javax.swing.JButton btnf6c5;
    private javax.swing.JButton btnf6c6;
    private javax.swing.JButton btnf6c7;
    private javax.swing.JButton btnf6c8;
    private javax.swing.JButton btnf7c1;
    private javax.swing.JButton btnf7c2;
    private javax.swing.JButton btnf7c3;
    private javax.swing.JButton btnf7c4;
    private javax.swing.JButton btnf7c5;
    private javax.swing.JButton btnf7c6;
    private javax.swing.JButton btnf7c7;
    private javax.swing.JButton btnf7c8;
    private javax.swing.JButton btnf8c1;
    private javax.swing.JButton btnf8c2;
    private javax.swing.JButton btnf8c3;
    private javax.swing.JButton btnf8c4;
    private javax.swing.JButton btnf8c5;
    private javax.swing.JButton btnf8c6;
    private javax.swing.JButton btnf8c7;
    private javax.swing.JButton btnf8c8;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
