/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package interfaz;

import cartas.Carta;
import controladores.ControladorJuego;
import java.awt.Font;
import java.awt.Image;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.Timer;
import juegos.Juego;

/**
 *
 * @author lenno
 */
public class jpnAvanzado extends javax.swing.JPanel {
     private ImageIcon dorsoIcon;
    private ControladorJuego controlador;
    JButton[] botones = new JButton[64];
    private Juego juego;

    private final String[] emojis = {
        "😀", "😎", "🤖", "👻",
        "🐶", "🐱", "🍕", "⚽",
        "🚗", "🚀", "🌟", "🔥",
        "🎮", "🎵", "🌈", "🍔",
        "🐸", "🐵", "🦊", "🐼",
        "🐨", "🦁", "🐯", "🐷",
        "🍎", "🍉", "🍓", "🍌",
        "🥑", "🍩", "🍪", "🎁"
    };

    /**
     * Creates new form jpnAvanzado
     */
    public jpnAvanzado(ControladorJuego controlador) {
        initComponents();
        this.controlador = controlador;
        botones[0] = btnf1c1;
        botones[1] = btnf1c2;
        botones[2] = btnf1c3;
        botones[3] = btnf1c4;
        botones[4] = btnf1c5;
        botones[5] = btnf1c6;
        botones[6] = btnf1c7;
        botones[7] = btnf1c8;
        botones[8] = btnf2c1;
        botones[9] = btnf2c2;
        botones[10] = btnf2c3;
        botones[11] = btnf2c4;
        botones[12] = btnf2c5;
        botones[13] = btnf2c6;
        botones[14] = btnf2c7;
        botones[15] = btnf2c8;
        botones[16] = btnf3c1;
        botones[17] = btnf3c2;
        botones[18] = btnf3c3;
        botones[19] = btnf3c4;
        botones[20] = btnf3c5;
        botones[21] = btnf3c6;
        botones[22] = btnf3c7;
        botones[23] = btnf3c8;
        botones[24] = btnf4c1;
        botones[25] = btnf4c2;
        botones[26] = btnf4c3;
        botones[27] = btnf4c4;
        botones[28] = btnf4c5;
        botones[29] = btnf4c6;
        botones[30] = btnf4c7;
        botones[31] = btnf4c8;
        botones[32] = btnf5c1;
        botones[33] = btnf5c2;
        botones[34] = btnf5c3;
        botones[35] = btnf5c4;
        botones[36] = btnf5c5;
        botones[37] = btnf5c6;
        botones[38] = btnf5c7;
        botones[39] = btnf5c8;
        botones[40] = btnf6c1;
        botones[41] = btnf6c2;
        botones[42] = btnf6c3;
        botones[43] = btnf6c4;
        botones[44] = btnf6c5;
        botones[45] = btnf6c6;
        botones[46] = btnf6c7;
        botones[47] = btnf6c8;
        botones[48] = btnf7c1;
        botones[49] = btnf7c2;
        botones[50] = btnf7c3;
        botones[51] = btnf7c4;
        botones[52] = btnf7c5;
        botones[53] = btnf7c6;
        botones[54] = btnf7c7;
        botones[55] = btnf7c8;
        botones[56] = btnf8c1;
        botones[57] = btnf8c2;
        botones[58] = btnf8c3;
        botones[59] = btnf8c4;
        botones[60] = btnf8c5;
        botones[61] = btnf8c6;
        botones[62] = btnf8c7;
        botones[63] = btnf8c8;

        Timer refresco = new Timer(200, e -> actualizarTablero());
        refresco.start();
        
        cargarDorso();
    }
    
     private void cargarDorso() {
        java.net.URL url = getClass().getResource("/interfaz/icon/jp.png.jpeg");
        ImageIcon original = new ImageIcon(url);
        int ancho = 49;
        int alto = 67;
        Image escalada = original.getImage().getScaledInstance(ancho, alto, Image.SCALE_SMOOTH);
        dorsoIcon = new ImageIcon(escalada);
        
        for (JButton boton : botones){
            boton.setIcon(dorsoIcon);
            boton.setFont(new Font("Segoe UI Emoji",Font.PLAIN,15));
        }
    }

    public void actualizarTablero() {
        Carta[][] cartas = controlador.getJuego().getTablero().getTablero();
        for (int i = 0; i < 8; i++) {
            for (int j = 0; j < 8; j++) {
                int indice = i * 8 + j;
                Carta carta = cartas[i][j];
                if (carta.isEstado() || carta.isEmparejada()) {
                    botones[indice].setIcon(null);
                    botones[indice].setText(
                            emojis[carta.getNombre() - 1]
                    );
                } else {
                    botones[indice].setText("");
                    botones[indice].setIcon(dorsoIcon);
                }
                botones[indice].setEnabled(
                        !carta.isEmparejada()
                );
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btnf1c7 = new javax.swing.JButton();
        btnf1c2 = new javax.swing.JButton();
        btnf1c5 = new javax.swing.JButton();
        btnf1c1 = new javax.swing.JButton();
        btnf1c3 = new javax.swing.JButton();
        btnf1c6 = new javax.swing.JButton();
        btnf1c4 = new javax.swing.JButton();
        btnf1c8 = new javax.swing.JButton();
        btnf2c4 = new javax.swing.JButton();
        btnf2c7 = new javax.swing.JButton();
        btnf2c2 = new javax.swing.JButton();
        btnf2c8 = new javax.swing.JButton();
        btnf2c5 = new javax.swing.JButton();
        btnf2c1 = new javax.swing.JButton();
        btnf2c3 = new javax.swing.JButton();
        btnf2c6 = new javax.swing.JButton();
        btnf3c4 = new javax.swing.JButton();
        btnf3c7 = new javax.swing.JButton();
        btnf3c2 = new javax.swing.JButton();
        btnf3c8 = new javax.swing.JButton();
        btnf3c5 = new javax.swing.JButton();
        btnf3c1 = new javax.swing.JButton();
        btnf4c4 = new javax.swing.JButton();
        btnf3c3 = new javax.swing.JButton();
        btnf4c7 = new javax.swing.JButton();
        btnf4c2 = new javax.swing.JButton();
        btnf4c8 = new javax.swing.JButton();
        btnf4c5 = new javax.swing.JButton();
        btnf4c1 = new javax.swing.JButton();
        btnf4c3 = new javax.swing.JButton();
        btnf4c6 = new javax.swing.JButton();
        btnf3c6 = new javax.swing.JButton();
        btnf7c2 = new javax.swing.JButton();
        btnf7c8 = new javax.swing.JButton();
        btnf7c5 = new javax.swing.JButton();
        btnf7c1 = new javax.swing.JButton();
        btnf8c4 = new javax.swing.JButton();
        btnf7c3 = new javax.swing.JButton();
        btnf5c4 = new javax.swing.JButton();
        btnf8c7 = new javax.swing.JButton();
        btnf8c2 = new javax.swing.JButton();
        btnf8c8 = new javax.swing.JButton();
        btnf5c7 = new javax.swing.JButton();
        btnf5c2 = new javax.swing.JButton();
        btnf5c8 = new javax.swing.JButton();
        btnf5c5 = new javax.swing.JButton();
        btnf5c1 = new javax.swing.JButton();
        btnf6c4 = new javax.swing.JButton();
        btnf5c3 = new javax.swing.JButton();
        btnf8c5 = new javax.swing.JButton();
        btnf8c1 = new javax.swing.JButton();
        btnf6c7 = new javax.swing.JButton();
        btnf8c3 = new javax.swing.JButton();
        btnf6c2 = new javax.swing.JButton();
        btnf8c6 = new javax.swing.JButton();
        btnf6c8 = new javax.swing.JButton();
        btnf7c6 = new javax.swing.JButton();
        btnf6c5 = new javax.swing.JButton();
        btnf6c1 = new javax.swing.JButton();
        btnf6c3 = new javax.swing.JButton();
        btnf6c6 = new javax.swing.JButton();
        btnf7c4 = new javax.swing.JButton();
        btnf7c7 = new javax.swing.JButton();
        btnf5c6 = new javax.swing.JButton();

        jPanel1.setPreferredSize(new java.awt.Dimension(510, 590));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnf1c7.setMaximumSize(new java.awt.Dimension(63, 5));
        btnf1c7.setMinimumSize(new java.awt.Dimension(63, 5));
        btnf1c7.addActionListener(this::btnf1c7ActionPerformed);
        jPanel1.add(btnf1c7, new org.netbeans.lib.awtextra.AbsoluteConstraints(365, 6, 49, 67));

        btnf1c2.setMaximumSize(new java.awt.Dimension(63, 5));
        btnf1c2.setMinimumSize(new java.awt.Dimension(63, 5));
        btnf1c2.addActionListener(this::btnf1c2ActionPerformed);
        jPanel1.add(btnf1c2, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 6, 49, 67));

        btnf1c5.setMaximumSize(new java.awt.Dimension(63, 5));
        btnf1c5.setMinimumSize(new java.awt.Dimension(63, 5));
        btnf1c5.addActionListener(this::btnf1c5ActionPerformed);
        jPanel1.add(btnf1c5, new org.netbeans.lib.awtextra.AbsoluteConstraints(255, 6, 49, 67));

        btnf1c1.setToolTipText("");
        btnf1c1.setMaximumSize(new java.awt.Dimension(63, 5));
        btnf1c1.setMinimumSize(new java.awt.Dimension(63, 5));
        btnf1c1.addActionListener(this::btnf1c1ActionPerformed);
        jPanel1.add(btnf1c1, new org.netbeans.lib.awtextra.AbsoluteConstraints(35, 6, 49, 67));

        btnf1c3.setMaximumSize(new java.awt.Dimension(63, 5));
        btnf1c3.setMinimumSize(new java.awt.Dimension(63, 5));
        btnf1c3.addActionListener(this::btnf1c3ActionPerformed);
        jPanel1.add(btnf1c3, new org.netbeans.lib.awtextra.AbsoluteConstraints(145, 6, 49, 67));

        btnf1c6.setMaximumSize(new java.awt.Dimension(63, 5));
        btnf1c6.setMinimumSize(new java.awt.Dimension(63, 5));
        btnf1c6.addActionListener(this::btnf1c6ActionPerformed);
        jPanel1.add(btnf1c6, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 6, 49, 67));

        btnf1c4.setMaximumSize(new java.awt.Dimension(63, 5));
        btnf1c4.setMinimumSize(new java.awt.Dimension(63, 5));
        btnf1c4.addActionListener(this::btnf1c4ActionPerformed);
        jPanel1.add(btnf1c4, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 6, 49, 67));

        btnf1c8.setMaximumSize(new java.awt.Dimension(63, 5));
        btnf1c8.setMinimumSize(new java.awt.Dimension(63, 5));
        btnf1c8.addActionListener(this::btnf1c8ActionPerformed);
        jPanel1.add(btnf1c8, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 6, 49, 67));

        btnf2c4.setMaximumSize(new java.awt.Dimension(63, 5));
        btnf2c4.setMinimumSize(new java.awt.Dimension(63, 5));
        btnf2c4.addActionListener(this::btnf2c4ActionPerformed);
        jPanel1.add(btnf2c4, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 79, 49, 67));

        btnf2c7.setMaximumSize(new java.awt.Dimension(63, 5));
        btnf2c7.setMinimumSize(new java.awt.Dimension(63, 5));
        btnf2c7.addActionListener(this::btnf2c7ActionPerformed);
        jPanel1.add(btnf2c7, new org.netbeans.lib.awtextra.AbsoluteConstraints(365, 79, 49, 67));

        btnf2c2.setMaximumSize(new java.awt.Dimension(63, 5));
        btnf2c2.setMinimumSize(new java.awt.Dimension(63, 5));
        btnf2c2.addActionListener(this::btnf2c2ActionPerformed);
        jPanel1.add(btnf2c2, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 79, 49, 67));

        btnf2c8.setMaximumSize(new java.awt.Dimension(63, 5));
        btnf2c8.setMinimumSize(new java.awt.Dimension(63, 5));
        btnf2c8.addActionListener(this::btnf2c8ActionPerformed);
        jPanel1.add(btnf2c8, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 79, 49, 67));

        btnf2c5.setMaximumSize(new java.awt.Dimension(63, 5));
        btnf2c5.setMinimumSize(new java.awt.Dimension(63, 5));
        btnf2c5.addActionListener(this::btnf2c5ActionPerformed);
        jPanel1.add(btnf2c5, new org.netbeans.lib.awtextra.AbsoluteConstraints(255, 79, 49, 67));

        btnf2c1.setMaximumSize(new java.awt.Dimension(63, 5));
        btnf2c1.setMinimumSize(new java.awt.Dimension(63, 5));
        btnf2c1.addActionListener(this::btnf2c1ActionPerformed);
        jPanel1.add(btnf2c1, new org.netbeans.lib.awtextra.AbsoluteConstraints(35, 79, 49, 67));

        btnf2c3.setMaximumSize(new java.awt.Dimension(63, 5));
        btnf2c3.setMinimumSize(new java.awt.Dimension(63, 5));
        btnf2c3.addActionListener(this::btnf2c3ActionPerformed);
        jPanel1.add(btnf2c3, new org.netbeans.lib.awtextra.AbsoluteConstraints(145, 79, 49, 67));

        btnf2c6.setMaximumSize(new java.awt.Dimension(63, 5));
        btnf2c6.setMinimumSize(new java.awt.Dimension(63, 5));
        btnf2c6.addActionListener(this::btnf2c6ActionPerformed);
        jPanel1.add(btnf2c6, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 79, 49, 67));

        btnf3c4.setMaximumSize(new java.awt.Dimension(63, 5));
        btnf3c4.setMinimumSize(new java.awt.Dimension(63, 5));
        btnf3c4.addActionListener(this::btnf3c4ActionPerformed);
        jPanel1.add(btnf3c4, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 152, 49, 67));

        btnf3c7.setMaximumSize(new java.awt.Dimension(63, 5));
        btnf3c7.setMinimumSize(new java.awt.Dimension(63, 5));
        btnf3c7.addActionListener(this::btnf3c7ActionPerformed);
        jPanel1.add(btnf3c7, new org.netbeans.lib.awtextra.AbsoluteConstraints(365, 152, 49, 67));

        btnf3c2.setMaximumSize(new java.awt.Dimension(63, 5));
        btnf3c2.setMinimumSize(new java.awt.Dimension(63, 5));
        btnf3c2.addActionListener(this::btnf3c2ActionPerformed);
        jPanel1.add(btnf3c2, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 152, 49, 67));

        btnf3c8.setMaximumSize(new java.awt.Dimension(63, 5));
        btnf3c8.setMinimumSize(new java.awt.Dimension(63, 5));
        btnf3c8.addActionListener(this::btnf3c8ActionPerformed);
        jPanel1.add(btnf3c8, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 152, 49, 67));

        btnf3c5.setMaximumSize(new java.awt.Dimension(63, 5));
        btnf3c5.setMinimumSize(new java.awt.Dimension(63, 5));
        btnf3c5.addActionListener(this::btnf3c5ActionPerformed);
        jPanel1.add(btnf3c5, new org.netbeans.lib.awtextra.AbsoluteConstraints(255, 152, 49, 67));

        btnf3c1.setMaximumSize(new java.awt.Dimension(63, 5));
        btnf3c1.setMinimumSize(new java.awt.Dimension(63, 5));
        btnf3c1.addActionListener(this::btnf3c1ActionPerformed);
        jPanel1.add(btnf3c1, new org.netbeans.lib.awtextra.AbsoluteConstraints(35, 152, 49, 67));

        btnf4c4.setMaximumSize(new java.awt.Dimension(63, 5));
        btnf4c4.setMinimumSize(new java.awt.Dimension(63, 5));
        btnf4c4.addActionListener(this::btnf4c4ActionPerformed);
        jPanel1.add(btnf4c4, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 225, 49, 67));

        btnf3c3.setMaximumSize(new java.awt.Dimension(63, 5));
        btnf3c3.setMinimumSize(new java.awt.Dimension(63, 5));
        btnf3c3.addActionListener(this::btnf3c3ActionPerformed);
        jPanel1.add(btnf3c3, new org.netbeans.lib.awtextra.AbsoluteConstraints(145, 152, 49, 67));

        btnf4c7.setMaximumSize(new java.awt.Dimension(63, 5));
        btnf4c7.setMinimumSize(new java.awt.Dimension(63, 5));
        btnf4c7.addActionListener(this::btnf4c7ActionPerformed);
        jPanel1.add(btnf4c7, new org.netbeans.lib.awtextra.AbsoluteConstraints(365, 225, 49, 67));

        btnf4c2.setMaximumSize(new java.awt.Dimension(63, 5));
        btnf4c2.setMinimumSize(new java.awt.Dimension(63, 5));
        btnf4c2.addActionListener(this::btnf4c2ActionPerformed);
        jPanel1.add(btnf4c2, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 225, 49, 67));

        btnf4c8.setMaximumSize(new java.awt.Dimension(63, 5));
        btnf4c8.setMinimumSize(new java.awt.Dimension(63, 5));
        btnf4c8.addActionListener(this::btnf4c8ActionPerformed);
        jPanel1.add(btnf4c8, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 225, 49, 67));

        btnf4c5.setMaximumSize(new java.awt.Dimension(63, 5));
        btnf4c5.setMinimumSize(new java.awt.Dimension(63, 5));
        btnf4c5.addActionListener(this::btnf4c5ActionPerformed);
        jPanel1.add(btnf4c5, new org.netbeans.lib.awtextra.AbsoluteConstraints(255, 225, 49, 67));

        btnf4c1.setMaximumSize(new java.awt.Dimension(63, 5));
        btnf4c1.setMinimumSize(new java.awt.Dimension(63, 5));
        btnf4c1.addActionListener(this::btnf4c1ActionPerformed);
        jPanel1.add(btnf4c1, new org.netbeans.lib.awtextra.AbsoluteConstraints(35, 225, 49, 67));

        btnf4c3.setMaximumSize(new java.awt.Dimension(63, 5));
        btnf4c3.setMinimumSize(new java.awt.Dimension(63, 5));
        btnf4c3.addActionListener(this::btnf4c3ActionPerformed);
        jPanel1.add(btnf4c3, new org.netbeans.lib.awtextra.AbsoluteConstraints(145, 225, 49, 67));

        btnf4c6.setMaximumSize(new java.awt.Dimension(63, 5));
        btnf4c6.setMinimumSize(new java.awt.Dimension(63, 5));
        btnf4c6.addActionListener(this::btnf4c6ActionPerformed);
        jPanel1.add(btnf4c6, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 225, 49, 67));

        btnf3c6.setMaximumSize(new java.awt.Dimension(63, 5));
        btnf3c6.setMinimumSize(new java.awt.Dimension(63, 5));
        btnf3c6.addActionListener(this::btnf3c6ActionPerformed);
        jPanel1.add(btnf3c6, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 152, 49, 67));

        btnf7c2.setMaximumSize(new java.awt.Dimension(63, 5));
        btnf7c2.setMinimumSize(new java.awt.Dimension(63, 5));
        btnf7c2.addActionListener(this::btnf7c2ActionPerformed);
        jPanel1.add(btnf7c2, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 444, 49, 67));

        btnf7c8.setMaximumSize(new java.awt.Dimension(63, 5));
        btnf7c8.setMinimumSize(new java.awt.Dimension(63, 5));
        btnf7c8.addActionListener(this::btnf7c8ActionPerformed);
        jPanel1.add(btnf7c8, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 444, 49, 67));

        btnf7c5.setMaximumSize(new java.awt.Dimension(63, 5));
        btnf7c5.setMinimumSize(new java.awt.Dimension(63, 5));
        btnf7c5.addActionListener(this::btnf7c5ActionPerformed);
        jPanel1.add(btnf7c5, new org.netbeans.lib.awtextra.AbsoluteConstraints(255, 444, 49, 67));

        btnf7c1.setMaximumSize(new java.awt.Dimension(63, 5));
        btnf7c1.setMinimumSize(new java.awt.Dimension(63, 5));
        btnf7c1.addActionListener(this::btnf7c1ActionPerformed);
        jPanel1.add(btnf7c1, new org.netbeans.lib.awtextra.AbsoluteConstraints(35, 444, 49, 67));

        btnf8c4.setMaximumSize(new java.awt.Dimension(63, 5));
        btnf8c4.setMinimumSize(new java.awt.Dimension(63, 5));
        btnf8c4.addActionListener(this::btnf8c4ActionPerformed);
        jPanel1.add(btnf8c4, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 517, 49, 67));

        btnf7c3.setMaximumSize(new java.awt.Dimension(63, 5));
        btnf7c3.setMinimumSize(new java.awt.Dimension(63, 5));
        btnf7c3.addActionListener(this::btnf7c3ActionPerformed);
        jPanel1.add(btnf7c3, new org.netbeans.lib.awtextra.AbsoluteConstraints(145, 444, 49, 67));

        btnf5c4.setMaximumSize(new java.awt.Dimension(63, 5));
        btnf5c4.setMinimumSize(new java.awt.Dimension(63, 5));
        btnf5c4.addActionListener(this::btnf5c4ActionPerformed);
        jPanel1.add(btnf5c4, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 298, 49, 67));

        btnf8c7.setMaximumSize(new java.awt.Dimension(63, 5));
        btnf8c7.setMinimumSize(new java.awt.Dimension(63, 5));
        btnf8c7.addActionListener(this::btnf8c7ActionPerformed);
        jPanel1.add(btnf8c7, new org.netbeans.lib.awtextra.AbsoluteConstraints(365, 517, 49, 67));

        btnf8c2.setMaximumSize(new java.awt.Dimension(63, 5));
        btnf8c2.setMinimumSize(new java.awt.Dimension(63, 5));
        btnf8c2.addActionListener(this::btnf8c2ActionPerformed);
        jPanel1.add(btnf8c2, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 517, 49, 67));

        btnf8c8.setMaximumSize(new java.awt.Dimension(63, 5));
        btnf8c8.setMinimumSize(new java.awt.Dimension(63, 5));
        btnf8c8.addActionListener(this::btnf8c8ActionPerformed);
        jPanel1.add(btnf8c8, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 517, 49, 67));

        btnf5c7.setMaximumSize(new java.awt.Dimension(63, 5));
        btnf5c7.setMinimumSize(new java.awt.Dimension(63, 5));
        btnf5c7.addActionListener(this::btnf5c7ActionPerformed);
        jPanel1.add(btnf5c7, new org.netbeans.lib.awtextra.AbsoluteConstraints(365, 298, 49, 67));

        btnf5c2.setMaximumSize(new java.awt.Dimension(63, 5));
        btnf5c2.setMinimumSize(new java.awt.Dimension(63, 5));
        btnf5c2.addActionListener(this::btnf5c2ActionPerformed);
        jPanel1.add(btnf5c2, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 298, 49, 67));

        btnf5c8.setMaximumSize(new java.awt.Dimension(63, 5));
        btnf5c8.setMinimumSize(new java.awt.Dimension(63, 5));
        btnf5c8.addActionListener(this::btnf5c8ActionPerformed);
        jPanel1.add(btnf5c8, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 298, 49, 67));

        btnf5c5.setMaximumSize(new java.awt.Dimension(63, 5));
        btnf5c5.setMinimumSize(new java.awt.Dimension(63, 5));
        btnf5c5.addActionListener(this::btnf5c5ActionPerformed);
        jPanel1.add(btnf5c5, new org.netbeans.lib.awtextra.AbsoluteConstraints(255, 298, 49, 67));

        btnf5c1.setMaximumSize(new java.awt.Dimension(63, 5));
        btnf5c1.setMinimumSize(new java.awt.Dimension(63, 5));
        btnf5c1.addActionListener(this::btnf5c1ActionPerformed);
        jPanel1.add(btnf5c1, new org.netbeans.lib.awtextra.AbsoluteConstraints(35, 298, 49, 67));

        btnf6c4.setMaximumSize(new java.awt.Dimension(63, 5));
        btnf6c4.setMinimumSize(new java.awt.Dimension(63, 5));
        btnf6c4.addActionListener(this::btnf6c4ActionPerformed);
        jPanel1.add(btnf6c4, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 371, 49, 67));

        btnf5c3.setMaximumSize(new java.awt.Dimension(63, 5));
        btnf5c3.setMinimumSize(new java.awt.Dimension(63, 5));
        btnf5c3.addActionListener(this::btnf5c3ActionPerformed);
        jPanel1.add(btnf5c3, new org.netbeans.lib.awtextra.AbsoluteConstraints(145, 298, 49, 67));

        btnf8c5.setMaximumSize(new java.awt.Dimension(63, 5));
        btnf8c5.setMinimumSize(new java.awt.Dimension(63, 5));
        btnf8c5.addActionListener(this::btnf8c5ActionPerformed);
        jPanel1.add(btnf8c5, new org.netbeans.lib.awtextra.AbsoluteConstraints(255, 517, 49, 67));

        btnf8c1.setMaximumSize(new java.awt.Dimension(63, 5));
        btnf8c1.setMinimumSize(new java.awt.Dimension(63, 5));
        btnf8c1.addActionListener(this::btnf8c1ActionPerformed);
        jPanel1.add(btnf8c1, new org.netbeans.lib.awtextra.AbsoluteConstraints(35, 517, 49, 67));

        btnf6c7.setMaximumSize(new java.awt.Dimension(63, 5));
        btnf6c7.setMinimumSize(new java.awt.Dimension(63, 5));
        btnf6c7.addActionListener(this::btnf6c7ActionPerformed);
        jPanel1.add(btnf6c7, new org.netbeans.lib.awtextra.AbsoluteConstraints(365, 371, 49, 67));

        btnf8c3.setMaximumSize(new java.awt.Dimension(63, 5));
        btnf8c3.setMinimumSize(new java.awt.Dimension(63, 5));
        btnf8c3.addActionListener(this::btnf8c3ActionPerformed);
        jPanel1.add(btnf8c3, new org.netbeans.lib.awtextra.AbsoluteConstraints(145, 517, 49, 67));

        btnf6c2.setMaximumSize(new java.awt.Dimension(63, 5));
        btnf6c2.setMinimumSize(new java.awt.Dimension(63, 5));
        btnf6c2.addActionListener(this::btnf6c2ActionPerformed);
        jPanel1.add(btnf6c2, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 371, 49, 67));

        btnf8c6.setMaximumSize(new java.awt.Dimension(63, 5));
        btnf8c6.setMinimumSize(new java.awt.Dimension(63, 5));
        btnf8c6.addActionListener(this::btnf8c6ActionPerformed);
        jPanel1.add(btnf8c6, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 517, 49, 67));

        btnf6c8.setMaximumSize(new java.awt.Dimension(63, 5));
        btnf6c8.setMinimumSize(new java.awt.Dimension(63, 5));
        btnf6c8.addActionListener(this::btnf6c8ActionPerformed);
        jPanel1.add(btnf6c8, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 371, 49, 67));

        btnf7c6.setMaximumSize(new java.awt.Dimension(63, 5));
        btnf7c6.setMinimumSize(new java.awt.Dimension(63, 5));
        btnf7c6.addActionListener(this::btnf7c6ActionPerformed);
        jPanel1.add(btnf7c6, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 444, 49, 67));

        btnf6c5.setMaximumSize(new java.awt.Dimension(63, 5));
        btnf6c5.setMinimumSize(new java.awt.Dimension(63, 5));
        btnf6c5.addActionListener(this::btnf6c5ActionPerformed);
        jPanel1.add(btnf6c5, new org.netbeans.lib.awtextra.AbsoluteConstraints(255, 371, 49, 67));

        btnf6c1.setMaximumSize(new java.awt.Dimension(63, 5));
        btnf6c1.setMinimumSize(new java.awt.Dimension(63, 5));
        btnf6c1.addActionListener(this::btnf6c1ActionPerformed);
        jPanel1.add(btnf6c1, new org.netbeans.lib.awtextra.AbsoluteConstraints(35, 371, 49, 67));

        btnf6c3.setMaximumSize(new java.awt.Dimension(63, 5));
        btnf6c3.setMinimumSize(new java.awt.Dimension(63, 5));
        btnf6c3.addActionListener(this::btnf6c3ActionPerformed);
        jPanel1.add(btnf6c3, new org.netbeans.lib.awtextra.AbsoluteConstraints(145, 371, 49, 67));

        btnf6c6.setMaximumSize(new java.awt.Dimension(63, 5));
        btnf6c6.setMinimumSize(new java.awt.Dimension(63, 5));
        btnf6c6.addActionListener(this::btnf6c6ActionPerformed);
        jPanel1.add(btnf6c6, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 371, 49, 67));

        btnf7c4.setMaximumSize(new java.awt.Dimension(63, 5));
        btnf7c4.setMinimumSize(new java.awt.Dimension(63, 5));
        btnf7c4.addActionListener(this::btnf7c4ActionPerformed);
        jPanel1.add(btnf7c4, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 444, 49, 67));

        btnf7c7.setMaximumSize(new java.awt.Dimension(63, 5));
        btnf7c7.setMinimumSize(new java.awt.Dimension(63, 5));
        btnf7c7.addActionListener(this::btnf7c7ActionPerformed);
        jPanel1.add(btnf7c7, new org.netbeans.lib.awtextra.AbsoluteConstraints(365, 444, 49, 67));

        btnf5c6.setMaximumSize(new java.awt.Dimension(63, 5));
        btnf5c6.setMinimumSize(new java.awt.Dimension(63, 5));
        btnf5c6.addActionListener(this::btnf5c6ActionPerformed);
        jPanel1.add(btnf5c6, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 298, 49, 67));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 498, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnf1c2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnf1c2ActionPerformed
        controlador.seleccionarCarta(0, 1);
        actualizarTablero();
    }//GEN-LAST:event_btnf1c2ActionPerformed

    private void btnf2c2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnf2c2ActionPerformed

        controlador.seleccionarCarta(1, 1);
        actualizarTablero();
    }//GEN-LAST:event_btnf2c2ActionPerformed

    private void btnf3c2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnf3c2ActionPerformed

        controlador.seleccionarCarta(2, 1);
        actualizarTablero();
    }//GEN-LAST:event_btnf3c2ActionPerformed

    private void btnf4c2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnf4c2ActionPerformed

        controlador.seleccionarCarta(3, 1);
        actualizarTablero();
    }//GEN-LAST:event_btnf4c2ActionPerformed

    private void btnf7c2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnf7c2ActionPerformed

        controlador.seleccionarCarta(6, 1);
        actualizarTablero();
    }//GEN-LAST:event_btnf7c2ActionPerformed

    private void btnf8c2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnf8c2ActionPerformed

        controlador.seleccionarCarta(7, 1);
        actualizarTablero();
    }//GEN-LAST:event_btnf8c2ActionPerformed

    private void btnf5c2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnf5c2ActionPerformed

        controlador.seleccionarCarta(4, 1);
        actualizarTablero();
    }//GEN-LAST:event_btnf5c2ActionPerformed

    private void btnf6c2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnf6c2ActionPerformed

        controlador.seleccionarCarta(5, 1);
        actualizarTablero();
    }//GEN-LAST:event_btnf6c2ActionPerformed

    private void btnf1c4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnf1c4ActionPerformed

        controlador.seleccionarCarta(0, 3);
        actualizarTablero();
    }//GEN-LAST:event_btnf1c4ActionPerformed

    private void btnf1c1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnf1c1ActionPerformed

        controlador.seleccionarCarta(0, 0);
        actualizarTablero();
    }//GEN-LAST:event_btnf1c1ActionPerformed

    private void btnf1c3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnf1c3ActionPerformed

        controlador.seleccionarCarta(0, 2);
        actualizarTablero();
    }//GEN-LAST:event_btnf1c3ActionPerformed

    private void btnf1c5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnf1c5ActionPerformed
        controlador.seleccionarCarta(0, 4);
        actualizarTablero();
    }//GEN-LAST:event_btnf1c5ActionPerformed

    private void btnf1c6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnf1c6ActionPerformed
        controlador.seleccionarCarta(0, 5);
        actualizarTablero();
    }//GEN-LAST:event_btnf1c6ActionPerformed

    private void btnf1c7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnf1c7ActionPerformed
        controlador.seleccionarCarta(0, 6);
        actualizarTablero();
    }//GEN-LAST:event_btnf1c7ActionPerformed

    private void btnf1c8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnf1c8ActionPerformed
        controlador.seleccionarCarta(0, 7);
        actualizarTablero();
    }//GEN-LAST:event_btnf1c8ActionPerformed

    private void btnf2c1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnf2c1ActionPerformed
        controlador.seleccionarCarta(1, 0);
        actualizarTablero();
    }//GEN-LAST:event_btnf2c1ActionPerformed

    private void btnf2c3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnf2c3ActionPerformed
        controlador.seleccionarCarta(1, 2);
        actualizarTablero();
    }//GEN-LAST:event_btnf2c3ActionPerformed

    private void btnf2c4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnf2c4ActionPerformed
        controlador.seleccionarCarta(1, 4);
        actualizarTablero();
    }//GEN-LAST:event_btnf2c4ActionPerformed

    private void btnf2c5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnf2c5ActionPerformed
        controlador.seleccionarCarta(1, 4);
        actualizarTablero();
    }//GEN-LAST:event_btnf2c5ActionPerformed

    private void btnf2c6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnf2c6ActionPerformed
        controlador.seleccionarCarta(1, 5);
        actualizarTablero();
    }//GEN-LAST:event_btnf2c6ActionPerformed

    private void btnf2c7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnf2c7ActionPerformed
        controlador.seleccionarCarta(1, 6);
        actualizarTablero();
    }//GEN-LAST:event_btnf2c7ActionPerformed

    private void btnf2c8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnf2c8ActionPerformed
        controlador.seleccionarCarta(1, 7);
        actualizarTablero();
    }//GEN-LAST:event_btnf2c8ActionPerformed

    private void btnf3c1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnf3c1ActionPerformed
        controlador.seleccionarCarta(2, 0);
        actualizarTablero();
    }//GEN-LAST:event_btnf3c1ActionPerformed

    private void btnf3c3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnf3c3ActionPerformed
        controlador.seleccionarCarta(2, 2);
        actualizarTablero();
    }//GEN-LAST:event_btnf3c3ActionPerformed

    private void btnf3c4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnf3c4ActionPerformed
        controlador.seleccionarCarta(2, 3);
        actualizarTablero();
    }//GEN-LAST:event_btnf3c4ActionPerformed

    private void btnf3c5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnf3c5ActionPerformed
        controlador.seleccionarCarta(2, 4);
        actualizarTablero();
    }//GEN-LAST:event_btnf3c5ActionPerformed

    private void btnf3c6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnf3c6ActionPerformed
        controlador.seleccionarCarta(2, 5);
        actualizarTablero();
    }//GEN-LAST:event_btnf3c6ActionPerformed

    private void btnf3c7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnf3c7ActionPerformed
        controlador.seleccionarCarta(2, 6);
        actualizarTablero();
    }//GEN-LAST:event_btnf3c7ActionPerformed

    private void btnf3c8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnf3c8ActionPerformed
        controlador.seleccionarCarta(2, 7);
        actualizarTablero();
    }//GEN-LAST:event_btnf3c8ActionPerformed

    private void btnf4c1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnf4c1ActionPerformed
        controlador.seleccionarCarta(3, 0);
        actualizarTablero();
    }//GEN-LAST:event_btnf4c1ActionPerformed

    private void btnf4c3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnf4c3ActionPerformed
        controlador.seleccionarCarta(3, 2);
        actualizarTablero();
    }//GEN-LAST:event_btnf4c3ActionPerformed

    private void btnf4c4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnf4c4ActionPerformed
        controlador.seleccionarCarta(3, 3);
        actualizarTablero();
    }//GEN-LAST:event_btnf4c4ActionPerformed

    private void btnf4c5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnf4c5ActionPerformed
        controlador.seleccionarCarta(3, 4);
        actualizarTablero();
    }//GEN-LAST:event_btnf4c5ActionPerformed

    private void btnf4c6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnf4c6ActionPerformed
        controlador.seleccionarCarta(3, 5);
        actualizarTablero();
    }//GEN-LAST:event_btnf4c6ActionPerformed

    private void btnf4c7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnf4c7ActionPerformed
        controlador.seleccionarCarta(3, 6);
        actualizarTablero();
    }//GEN-LAST:event_btnf4c7ActionPerformed

    private void btnf4c8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnf4c8ActionPerformed
        controlador.seleccionarCarta(3, 7);
        actualizarTablero();
    }//GEN-LAST:event_btnf4c8ActionPerformed

    private void btnf5c1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnf5c1ActionPerformed
        controlador.seleccionarCarta(4, 0);
        actualizarTablero();
    }//GEN-LAST:event_btnf5c1ActionPerformed

    private void btnf5c3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnf5c3ActionPerformed
        controlador.seleccionarCarta(4, 2);
        actualizarTablero();
    }//GEN-LAST:event_btnf5c3ActionPerformed

    private void btnf5c4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnf5c4ActionPerformed
        controlador.seleccionarCarta(4, 3);
        actualizarTablero();
    }//GEN-LAST:event_btnf5c4ActionPerformed

    private void btnf5c5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnf5c5ActionPerformed
        controlador.seleccionarCarta(4, 4);
        actualizarTablero();
    }//GEN-LAST:event_btnf5c5ActionPerformed

    private void btnf5c6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnf5c6ActionPerformed
        controlador.seleccionarCarta(4, 5);
        actualizarTablero();
    }//GEN-LAST:event_btnf5c6ActionPerformed

    private void btnf5c7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnf5c7ActionPerformed
        controlador.seleccionarCarta(4, 6);
        actualizarTablero();
    }//GEN-LAST:event_btnf5c7ActionPerformed

    private void btnf5c8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnf5c8ActionPerformed
        controlador.seleccionarCarta(4, 7);
        actualizarTablero();
    }//GEN-LAST:event_btnf5c8ActionPerformed

    private void btnf6c1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnf6c1ActionPerformed
        controlador.seleccionarCarta(5, 0);
        actualizarTablero();
    }//GEN-LAST:event_btnf6c1ActionPerformed

    private void btnf6c3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnf6c3ActionPerformed
        controlador.seleccionarCarta(5, 2);
        actualizarTablero();
    }//GEN-LAST:event_btnf6c3ActionPerformed

    private void btnf6c4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnf6c4ActionPerformed
        controlador.seleccionarCarta(5, 3);
        actualizarTablero();
    }//GEN-LAST:event_btnf6c4ActionPerformed

    private void btnf6c5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnf6c5ActionPerformed
        controlador.seleccionarCarta(5, 4);
        actualizarTablero();
    }//GEN-LAST:event_btnf6c5ActionPerformed

    private void btnf6c6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnf6c6ActionPerformed
        controlador.seleccionarCarta(5, 5);
        actualizarTablero();
    }//GEN-LAST:event_btnf6c6ActionPerformed

    private void btnf6c7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnf6c7ActionPerformed
        controlador.seleccionarCarta(5, 6);
        actualizarTablero();
    }//GEN-LAST:event_btnf6c7ActionPerformed

    private void btnf6c8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnf6c8ActionPerformed
        controlador.seleccionarCarta(5, 7);
        actualizarTablero();
    }//GEN-LAST:event_btnf6c8ActionPerformed

    private void btnf7c1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnf7c1ActionPerformed
        controlador.seleccionarCarta(6, 0);
        actualizarTablero();
    }//GEN-LAST:event_btnf7c1ActionPerformed

    private void btnf7c3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnf7c3ActionPerformed
        controlador.seleccionarCarta(6, 2);
        actualizarTablero();
    }//GEN-LAST:event_btnf7c3ActionPerformed

    private void btnf7c4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnf7c4ActionPerformed
        controlador.seleccionarCarta(6, 3);
        actualizarTablero();
    }//GEN-LAST:event_btnf7c4ActionPerformed

    private void btnf7c5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnf7c5ActionPerformed
        controlador.seleccionarCarta(6, 4);
        actualizarTablero();
    }//GEN-LAST:event_btnf7c5ActionPerformed

    private void btnf7c6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnf7c6ActionPerformed
        controlador.seleccionarCarta(6, 5);
        actualizarTablero();
    }//GEN-LAST:event_btnf7c6ActionPerformed

    private void btnf7c7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnf7c7ActionPerformed
        controlador.seleccionarCarta(6, 6);
        actualizarTablero();
    }//GEN-LAST:event_btnf7c7ActionPerformed

    private void btnf7c8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnf7c8ActionPerformed
        controlador.seleccionarCarta(6, 7);
        actualizarTablero();
    }//GEN-LAST:event_btnf7c8ActionPerformed

    private void btnf8c1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnf8c1ActionPerformed
        controlador.seleccionarCarta(7, 0);
        actualizarTablero();
    }//GEN-LAST:event_btnf8c1ActionPerformed

    private void btnf8c3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnf8c3ActionPerformed
        controlador.seleccionarCarta(7, 2);
        actualizarTablero();
    }//GEN-LAST:event_btnf8c3ActionPerformed

    private void btnf8c4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnf8c4ActionPerformed
        controlador.seleccionarCarta(7, 3);
        actualizarTablero();
    }//GEN-LAST:event_btnf8c4ActionPerformed

    private void btnf8c5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnf8c5ActionPerformed
        controlador.seleccionarCarta(7, 4);
        actualizarTablero();
    }//GEN-LAST:event_btnf8c5ActionPerformed

    private void btnf8c6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnf8c6ActionPerformed
        controlador.seleccionarCarta(7, 5);
        actualizarTablero();
    }//GEN-LAST:event_btnf8c6ActionPerformed

    private void btnf8c7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnf8c7ActionPerformed
        controlador.seleccionarCarta(7, 6);
        actualizarTablero();
    }//GEN-LAST:event_btnf8c7ActionPerformed

    private void btnf8c8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnf8c8ActionPerformed
        controlador.seleccionarCarta(7, 7);
        actualizarTablero();
    }//GEN-LAST:event_btnf8c8ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnf1c1;
    private javax.swing.JButton btnf1c2;
    private javax.swing.JButton btnf1c3;
    private javax.swing.JButton btnf1c4;
    private javax.swing.JButton btnf1c5;
    private javax.swing.JButton btnf1c6;
    private javax.swing.JButton btnf1c7;
    private javax.swing.JButton btnf1c8;
    private javax.swing.JButton btnf2c1;
    private javax.swing.JButton btnf2c2;
    private javax.swing.JButton btnf2c3;
    private javax.swing.JButton btnf2c4;
    private javax.swing.JButton btnf2c5;
    private javax.swing.JButton btnf2c6;
    private javax.swing.JButton btnf2c7;
    private javax.swing.JButton btnf2c8;
    private javax.swing.JButton btnf3c1;
    private javax.swing.JButton btnf3c2;
    private javax.swing.JButton btnf3c3;
    private javax.swing.JButton btnf3c4;
    private javax.swing.JButton btnf3c5;
    private javax.swing.JButton btnf3c6;
    private javax.swing.JButton btnf3c7;
    private javax.swing.JButton btnf3c8;
    private javax.swing.JButton btnf4c1;
    private javax.swing.JButton btnf4c2;
    private javax.swing.JButton btnf4c3;
    private javax.swing.JButton btnf4c4;
    private javax.swing.JButton btnf4c5;
    private javax.swing.JButton btnf4c6;
    private javax.swing.JButton btnf4c7;
    private javax.swing.JButton btnf4c8;
    private javax.swing.JButton btnf5c1;
    private javax.swing.JButton btnf5c2;
    private javax.swing.JButton btnf5c3;
    private javax.swing.JButton btnf5c4;
    private javax.swing.JButton btnf5c5;
    private javax.swing.JButton btnf5c6;
    private javax.swing.JButton btnf5c7;
    private javax.swing.JButton btnf5c8;
    private javax.swing.JButton btnf6c1;
    private javax.swing.JButton btnf6c2;
    private javax.swing.JButton btnf6c3;
    private javax.swing.JButton btnf6c4;
    private javax.swing.JButton btnf6c5;
    private javax.swing.JButton btnf6c6;
    private javax.swing.JButton btnf6c7;
    private javax.swing.JButton btnf6c8;
    private javax.swing.JButton btnf7c1;
    private javax.swing.JButton btnf7c2;
    private javax.swing.JButton btnf7c3;
    private javax.swing.JButton btnf7c4;
    private javax.swing.JButton btnf7c5;
    private javax.swing.JButton btnf7c6;
    private javax.swing.JButton btnf7c7;
    private javax.swing.JButton btnf7c8;
    private javax.swing.JButton btnf8c1;
    private javax.swing.JButton btnf8c2;
    private javax.swing.JButton btnf8c3;
    private javax.swing.JButton btnf8c4;
    private javax.swing.JButton btnf8c5;
    private javax.swing.JButton btnf8c6;
    private javax.swing.JButton btnf8c7;
    private javax.swing.JButton btnf8c8;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
