/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package interfaz;

import cartas.Carta;
import controladores.ControladorJuego;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.Timer;
import java.awt.Image;


/**
 *
 * @author andre
 */
public class jpnFacil extends javax.swing.JPanel {
    private ControladorJuego controlador;
    private ImageIcon dorsoIcon;
     
     JButton[] botones = new JButton [16];
    /**
     * Creates new form jpnFacil
     */
    private final String[] emojis = {
    "😀", "😎", "🤖", "👻",
    "🐶", "🐱", "🍕", "⚽"
};
    public jpnFacil(ControladorJuego controlador) {
        initComponents();
        this.controlador = controlador;
        
    botones[0] = btnf1c1;
    botones[1] = btnf1c2;
    botones[2] = btnf1c3;
    botones[3] = btnf1c4;
    botones[4] = btnf2c1;
    botones[5]= btnf2c2;
    botones[6] = btnf2c3;
    botones[7] = btnf2c4;
    botones[8] = btnf3c1;
    botones[9]= btnf3c2;
    botones[10] = btnf3c3;
    botones[11] = btnf3c4;
    botones[12] = btnf4c1;
    botones[13]= btnf4c2;
    botones[14]= btnf4c3;
    botones[15] = btnf4c4;   
    
     Timer refresco = new Timer(200, e -> actualizarTablero());
        refresco.start();
        
        
        cargarDorso();
    }
    
    private void cargarDorso() {
        java.net.URL url = getClass().getResource("/interfaz/icon/jp.png.jpeg");
        ImageIcon original = new ImageIcon(url);
        int ancho = 104;
        int alto = 138;
        Image escalada = original.getImage().getScaledInstance(ancho, alto, Image.SCALE_SMOOTH);
        dorsoIcon = new ImageIcon(escalada);
        
        for (JButton boton : botones){
            boton.setIcon(dorsoIcon);
        }
    }
   
    public void actualizarTablero(){
        Carta [][] cartas = controlador.getJuego().getTablero().getTablero();
        for (int i = 0; i < 4; i++) {
            for (int j = 0; j < 4; j++) {
                int indice = i* 4 +j;
                Carta carta = cartas[i][j];
                if (carta.isEstado() || carta.isEmparejada()){
                    botones[indice].setIcon(null);
                    botones[indice].setText(emojis[carta.getNombre()-1]);                   
                }else{
                    botones[indice].setText("");
                    botones[indice].setIcon(dorsoIcon);
                }
                botones[indice].setEnabled(!carta.isEmparejada());
            }                
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnf1c1 = new javax.swing.JButton();
        btnf1c2 = new javax.swing.JButton();
        btnf1c3 = new javax.swing.JButton();
        btnf1c4 = new javax.swing.JButton();
        btnf2c1 = new javax.swing.JButton();
        btnf2c2 = new javax.swing.JButton();
        btnf2c3 = new javax.swing.JButton();
        btnf2c4 = new javax.swing.JButton();
        btnf3c1 = new javax.swing.JButton();
        btnf3c2 = new javax.swing.JButton();
        btnf3c3 = new javax.swing.JButton();
        btnf3c4 = new javax.swing.JButton();
        btnf4c1 = new javax.swing.JButton();
        btnf4c2 = new javax.swing.JButton();
        btnf4c3 = new javax.swing.JButton();
        btnf4c4 = new javax.swing.JButton();

        setPreferredSize(new java.awt.Dimension(510, 590));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnf1c1.addActionListener(this::btnf1c1ActionPerformed);
        add(btnf1c1, new org.netbeans.lib.awtextra.AbsoluteConstraints(34, 6, 104, 138));

        btnf1c2.addActionListener(this::btnf1c2ActionPerformed);
        add(btnf1c2, new org.netbeans.lib.awtextra.AbsoluteConstraints(148, 6, 104, 138));

        btnf1c3.addActionListener(this::btnf1c3ActionPerformed);
        add(btnf1c3, new org.netbeans.lib.awtextra.AbsoluteConstraints(262, 6, 104, 138));

        btnf1c4.addActionListener(this::btnf1c4ActionPerformed);
        add(btnf1c4, new org.netbeans.lib.awtextra.AbsoluteConstraints(376, 6, 104, 138));

        btnf2c1.addActionListener(this::btnf2c1ActionPerformed);
        add(btnf2c1, new org.netbeans.lib.awtextra.AbsoluteConstraints(34, 154, 104, 138));

        btnf2c2.addActionListener(this::btnf2c2ActionPerformed);
        add(btnf2c2, new org.netbeans.lib.awtextra.AbsoluteConstraints(148, 154, 104, 138));

        btnf2c3.addActionListener(this::btnf2c3ActionPerformed);
        add(btnf2c3, new org.netbeans.lib.awtextra.AbsoluteConstraints(262, 154, 104, 138));

        btnf2c4.addActionListener(this::btnf2c4ActionPerformed);
        add(btnf2c4, new org.netbeans.lib.awtextra.AbsoluteConstraints(376, 154, 104, 138));

        btnf3c1.addActionListener(this::btnf3c1ActionPerformed);
        add(btnf3c1, new org.netbeans.lib.awtextra.AbsoluteConstraints(34, 302, 104, 138));

        btnf3c2.addActionListener(this::btnf3c2ActionPerformed);
        add(btnf3c2, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 302, 104, 138));

        btnf3c3.addActionListener(this::btnf3c3ActionPerformed);
        add(btnf3c3, new org.netbeans.lib.awtextra.AbsoluteConstraints(264, 302, 104, 138));

        btnf3c4.addActionListener(this::btnf3c4ActionPerformed);
        add(btnf3c4, new org.netbeans.lib.awtextra.AbsoluteConstraints(378, 302, 104, 138));

        btnf4c1.addActionListener(this::btnf4c1ActionPerformed);
        add(btnf4c1, new org.netbeans.lib.awtextra.AbsoluteConstraints(34, 450, 104, 138));

        btnf4c2.addActionListener(this::btnf4c2ActionPerformed);
        add(btnf4c2, new org.netbeans.lib.awtextra.AbsoluteConstraints(148, 450, 104, 138));

        btnf4c3.addActionListener(this::btnf4c3ActionPerformed);
        add(btnf4c3, new org.netbeans.lib.awtextra.AbsoluteConstraints(262, 450, 104, 138));

        btnf4c4.addActionListener(this::btnf4c4ActionPerformed);
        add(btnf4c4, new org.netbeans.lib.awtextra.AbsoluteConstraints(378, 450, 104, 138));
    }// </editor-fold>//GEN-END:initComponents

    private void btnf2c1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnf2c1ActionPerformed
         controlador.seleccionarCarta(1,0);
         actualizarTablero();
    }//GEN-LAST:event_btnf2c1ActionPerformed

    private void btnf1c1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnf1c1ActionPerformed
        controlador.seleccionarCarta(0,0);
        actualizarTablero();
    }//GEN-LAST:event_btnf1c1ActionPerformed

    private void btnf2c3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnf2c3ActionPerformed
        controlador.seleccionarCarta(1,2);
        actualizarTablero();
    }//GEN-LAST:event_btnf2c3ActionPerformed

    private void btnf1c3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnf1c3ActionPerformed
        controlador.seleccionarCarta(0,2);
        actualizarTablero();
    }//GEN-LAST:event_btnf1c3ActionPerformed

    private void btnf1c8Abtnf1c1rformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnf1c8ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnf1c8ActionPerformed

    private void btnf2c2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnf2c2ActionPerformed
         controlador.seleccionarCarta(1,1);
         actualizarTablero();
    }//GEN-LAST:event_btnf2c2ActionPerformed

    private void btnf4c1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnf4c1ActionPerformed
         controlador.seleccionarCarta(3,0);
         actualizarTablero();
    }//GEN-LAST:event_btnf4c1ActionPerformed

    private void btnf3c1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnf3c1ActionPerformed
        controlador.seleccionarCarta(2,0);
        actualizarTablero();
    }//GEN-LAST:event_btnf3c1ActionPerformed

    private void btnf4c3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnf4c3ActionPerformed
        controlador.seleccionarCarta(3,2);
        actualizarTablero();
    }//GEN-LAST:event_btnf4c3ActionPerformed

    private void btnf3c3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnf3c3ActionPerformed
         controlador.seleccionarCarta(2,2);
         actualizarTablero();
    }//GEN-LAST:event_btnf3c3ActionPerformed

    private void btnf3c2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnf3c2ActionPerformed
         controlador.seleccionarCarta(2,1);
         actualizarTablero();
    }//GEN-LAST:event_btnf3c2ActionPerformed

    private void btnf4c2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnf4c2ActionPerformed
        controlador.seleccionarCarta(3,1);
        actualizarTablero();
    }//GEN-LAST:event_btnf4c2ActionPerformed

    private void btnf2c4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnf2c4ActionPerformed
         controlador.seleccionarCarta(1,3);
         actualizarTablero();
    }//GEN-LAST:event_btnf2c4ActionPerformed

    private void btnf1c4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnf1c4ActionPerformed
         controlador.seleccionarCarta(0,3);
         actualizarTablero();
    }//GEN-LAST:event_btnf1c4ActionPerformed

    private void btnf4c4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnf4c4ActionPerformed
        controlador.seleccionarCarta(3,3);
        actualizarTablero();
    }//GEN-LAST:event_btnf4c4ActionPerformed

    private void btnf3c4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnf3c4ActionPerformed
         controlador.seleccionarCarta(2,3);
         actualizarTablero();
    }//GEN-LAST:event_btnf3c4ActionPerformed

    private void btnf1c2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnf1c2ActionPerformed
         controlador.seleccionarCarta(0,1);
         actualizarTablero();
    }//GEN-LAST:event_btnf1c2ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnf1c1;
    private javax.swing.JButton btnf1c2;
    private javax.swing.JButton btnf1c3;
    private javax.swing.JButton btnf1c4;
    private javax.swing.JButton btnf2c1;
    private javax.swing.JButton btnf2c2;
    private javax.swing.JButton btnf2c3;
    private javax.swing.JButton btnf2c4;
    private javax.swing.JButton btnf3c1;
    private javax.swing.JButton btnf3c2;
    private javax.swing.JButton btnf3c3;
    private javax.swing.JButton btnf3c4;
    private javax.swing.JButton btnf4c1;
    private javax.swing.JButton btnf4c2;
    private javax.swing.JButton btnf4c3;
    private javax.swing.JButton btnf4c4;
    // End of variables declaration//GEN-END:variables
}
