/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package interfaz;

/**
 *
 * @author andre
 */
public class jpnFacil extends javax.swing.JPanel {

    /**
     * Creates new form jpnFacil
     */
    
    public jpnFacil() {
        initComponents();
                
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnf1c4 = new javax.swing.JButton();
        btnf4c4 = new javax.swing.JButton();
        btnf1c5 = new javax.swing.JButton();

        setPreferredSize(new java.awt.Dimension(900, 400));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnf1c4.addActionListener(this::btnf1c4ActionPerformed);
        add(btnf1c4, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 20, 40, 50));

        btnf4c4.addActionListener(this::btnf4c4ActionPerformed);
        add(btnf4c4, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 270, 50, 70));

        btnf1c5.addActionListener(this::btnf1c5ActionPerformed);
        add(btnf1c5, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 0, 40, 50));
    }// </editor-fold>//GEN-END:initComponents

    private void btnf1c4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnf1c4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnf1c4ActionPerformed

    private void btnf1c5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnf1c5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnf1c5ActionPerformed

    private void btnf4c4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnf4c4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnf4c4ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnf1c4;
    private javax.swing.JButton btnf1c5;
    private javax.swing.JButton btnf4c4;
    // End of variables declaration//GEN-END:variables
}
