/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package interfaz;

import cartas.Carta;
import controladores.ControladorJuego;
import java.awt.Font;
import java.awt.Image;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.Timer;


/**
 *
 * @author Yumor
 */
public class jpnIntermedio extends javax.swing.JPanel {
    private ControladorJuego controlador;
    private ImageIcon dorsoIcon;

    JButton[] botones = new JButton[32];

    private final String[] emojis = {
        "😀", "😎", "🤖", "👻",
        "🐶", "🐱", "🍕", "⚽",
        "🚗", "🚀", "🌟", "🔥",
        "🎮", "🎵", "🌈", "🍔"
    };

    /**
     * Creates new form jpnIntermedio
     */
    public jpnIntermedio(ControladorJuego controlador) {

        initComponents();

        this.controlador = controlador;
        botones[0] = btnf1c1;
        botones[1] = btnf1c2;
        botones[2] = btnf1c3;
        botones[3] = btnf1c4;
        botones[4] = btnf1c5;
        botones[5] = btnf1c6;
        botones[6] = btnf1c7;
        botones[7] = btnf1c8;
        botones[8] = btnf2c1;
        botones[9] = btnf2c2;
        botones[10] = btnf2c3;
        botones[11] = btnf2c4;
        botones[12] = btnf2c5;
        botones[13] = btnf2c6;
        botones[14] = btnf2c7;
        botones[15] = btnf2c8;
        botones[16] = btnf3c1;
        botones[17] = btnf3c2;
        botones[18] = btnf3c3;
        botones[19] = btnf3c4;
        botones[20] = btnf3c5;
        botones[21] = btnf3c6;
        botones[22] = btnf3c7;
        botones[23] = btnf3c8;
        botones[24] = btnf4c1;
        botones[25] = btnf4c2;
        botones[26] = btnf4c3;
        botones[27] = btnf4c4;
        botones[28] = btnf4c5;
        botones[29] = btnf4c6;
        botones[30] = btnf4c7;
        botones[31] = btnf4c8;

        Timer refresco = new Timer(200, e -> actualizarTablero());
        refresco.start();
        
        cargarDorso();
    }
    
    private void cargarDorso() {
        java.net.URL url = getClass().getResource("/interfaz/icon/jp.png.jpeg");
        ImageIcon original = new ImageIcon(url);
        int ancho = 55;
        int alto = 100;
        Image escalada = original.getImage().getScaledInstance(ancho, alto, Image.SCALE_SMOOTH);
        dorsoIcon = new ImageIcon(escalada);
        
        for (JButton boton : botones){
            boton.setIcon(dorsoIcon);
            boton.setFont(new Font("Segoe UI Emoji",Font.PLAIN,20));
        }
    }

    public void actualizarTablero() {
        Carta[][] cartas = controlador.getJuego().getTablero().getTablero();
        for (int i = 0; i < 4; i++) {
            for (int j = 0; j < 8; j++) {
                int indice = i * 8 + j;
                Carta carta = cartas[i][j];
                if (carta.isEstado() || carta.isEmparejada()) {
                  botones[indice].setIcon(null);
                  botones[indice].setText(
                  emojis[carta.getNombre() - 1]);
                } else {
                  botones[indice].setText("");
                  botones[indice].setIcon(dorsoIcon);
                }
            botones[indice].setEnabled(!carta.isEmparejada()
            );
        }
    }
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnf1c1 = new javax.swing.JButton();
        btnf1c2 = new javax.swing.JButton();
        btnf1c3 = new javax.swing.JButton();
        btnf1c4 = new javax.swing.JButton();
        btnf1c5 = new javax.swing.JButton();
        btnf1c6 = new javax.swing.JButton();
        btnf1c7 = new javax.swing.JButton();
        btnf1c8 = new javax.swing.JButton();
        btnf2c1 = new javax.swing.JButton();
        btnf2c2 = new javax.swing.JButton();
        btnf2c3 = new javax.swing.JButton();
        btnf2c4 = new javax.swing.JButton();
        btnf2c5 = new javax.swing.JButton();
        btnf2c6 = new javax.swing.JButton();
        btnf2c7 = new javax.swing.JButton();
        btnf2c8 = new javax.swing.JButton();
        btnf3c1 = new javax.swing.JButton();
        btnf3c2 = new javax.swing.JButton();
        btnf3c3 = new javax.swing.JButton();
        btnf3c4 = new javax.swing.JButton();
        btnf3c5 = new javax.swing.JButton();
        btnf3c6 = new javax.swing.JButton();
        btnf3c7 = new javax.swing.JButton();
        btnf3c8 = new javax.swing.JButton();
        btnf4c1 = new javax.swing.JButton();
        btnf4c2 = new javax.swing.JButton();
        btnf4c3 = new javax.swing.JButton();
        btnf4c4 = new javax.swing.JButton();
        btnf4c5 = new javax.swing.JButton();
        btnf4c6 = new javax.swing.JButton();
        btnf4c7 = new javax.swing.JButton();
        btnf4c8 = new javax.swing.JButton();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnf1c1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnf1c1ActionPerformed(evt);
            }
        });
        add(btnf1c1, new org.netbeans.lib.awtextra.AbsoluteConstraints(18, 43, 55, 100));

        btnf1c2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnf1c2ActionPerformed(evt);
            }
        });
        add(btnf1c2, new org.netbeans.lib.awtextra.AbsoluteConstraints(79, 43, 55, 100));

        btnf1c3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnf1c3ActionPerformed(evt);
            }
        });
        add(btnf1c3, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 43, 55, 100));

        btnf1c4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnf1c4ActionPerformed(evt);
            }
        });
        add(btnf1c4, new org.netbeans.lib.awtextra.AbsoluteConstraints(201, 43, 55, 100));

        btnf1c5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnf1c5ActionPerformed(evt);
            }
        });
        add(btnf1c5, new org.netbeans.lib.awtextra.AbsoluteConstraints(262, 43, 55, 100));

        btnf1c6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnf1c6ActionPerformed(evt);
            }
        });
        add(btnf1c6, new org.netbeans.lib.awtextra.AbsoluteConstraints(323, 43, 55, 100));

        btnf1c7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnf1c7ActionPerformed(evt);
            }
        });
        add(btnf1c7, new org.netbeans.lib.awtextra.AbsoluteConstraints(384, 43, 55, 100));

        btnf1c8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnf1c8ActionPerformed(evt);
            }
        });
        add(btnf1c8, new org.netbeans.lib.awtextra.AbsoluteConstraints(445, 43, 55, 100));

        btnf2c1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnf2c1ActionPerformed(evt);
            }
        });
        add(btnf2c1, new org.netbeans.lib.awtextra.AbsoluteConstraints(18, 169, 55, 100));

        btnf2c2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnf2c2ActionPerformed(evt);
            }
        });
        add(btnf2c2, new org.netbeans.lib.awtextra.AbsoluteConstraints(79, 169, 55, 100));

        btnf2c3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnf2c3ActionPerformed(evt);
            }
        });
        add(btnf2c3, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 169, 55, 100));

        btnf2c4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnf2c4ActionPerformed(evt);
            }
        });
        add(btnf2c4, new org.netbeans.lib.awtextra.AbsoluteConstraints(201, 169, 55, 100));

        btnf2c5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnf2c5ActionPerformed(evt);
            }
        });
        add(btnf2c5, new org.netbeans.lib.awtextra.AbsoluteConstraints(262, 169, 55, 100));

        btnf2c6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnf2c6ActionPerformed(evt);
            }
        });
        add(btnf2c6, new org.netbeans.lib.awtextra.AbsoluteConstraints(323, 169, 55, 100));

        btnf2c7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnf2c7ActionPerformed(evt);
            }
        });
        add(btnf2c7, new org.netbeans.lib.awtextra.AbsoluteConstraints(384, 169, 55, 100));

        btnf2c8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnf2c8ActionPerformed(evt);
            }
        });
        add(btnf2c8, new org.netbeans.lib.awtextra.AbsoluteConstraints(445, 169, 55, 100));

        btnf3c1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnf3c1ActionPerformed(evt);
            }
        });
        add(btnf3c1, new org.netbeans.lib.awtextra.AbsoluteConstraints(18, 295, 55, 100));

        btnf3c2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnf3c2ActionPerformed(evt);
            }
        });
        add(btnf3c2, new org.netbeans.lib.awtextra.AbsoluteConstraints(79, 295, 55, 100));

        btnf3c3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnf3c3ActionPerformed(evt);
            }
        });
        add(btnf3c3, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 295, 55, 100));

        btnf3c4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnf3c4ActionPerformed(evt);
            }
        });
        add(btnf3c4, new org.netbeans.lib.awtextra.AbsoluteConstraints(201, 295, 55, 100));

        btnf3c5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnf3c5ActionPerformed(evt);
            }
        });
        add(btnf3c5, new org.netbeans.lib.awtextra.AbsoluteConstraints(262, 295, 55, 100));

        btnf3c6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnf3c6ActionPerformed(evt);
            }
        });
        add(btnf3c6, new org.netbeans.lib.awtextra.AbsoluteConstraints(323, 295, 55, 100));

        btnf3c7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnf3c7ActionPerformed(evt);
            }
        });
        add(btnf3c7, new org.netbeans.lib.awtextra.AbsoluteConstraints(384, 295, 55, 100));

        btnf3c8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnf3c8ActionPerformed(evt);
            }
        });
        add(btnf3c8, new org.netbeans.lib.awtextra.AbsoluteConstraints(445, 295, 55, 100));

        btnf4c1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnf4c1ActionPerformed(evt);
            }
        });
        add(btnf4c1, new org.netbeans.lib.awtextra.AbsoluteConstraints(18, 421, 55, 100));

        btnf4c2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnf4c2ActionPerformed(evt);
            }
        });
        add(btnf4c2, new org.netbeans.lib.awtextra.AbsoluteConstraints(79, 421, 55, 100));

        btnf4c3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnf4c3ActionPerformed(evt);
            }
        });
        add(btnf4c3, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 421, 55, 100));

        btnf4c4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnf4c4ActionPerformed(evt);
            }
        });
        add(btnf4c4, new org.netbeans.lib.awtextra.AbsoluteConstraints(201, 421, 55, 100));

        btnf4c5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnf4c5ActionPerformed(evt);
            }
        });
        add(btnf4c5, new org.netbeans.lib.awtextra.AbsoluteConstraints(262, 421, 55, 100));

        btnf4c6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnf4c6ActionPerformed(evt);
            }
        });
        add(btnf4c6, new org.netbeans.lib.awtextra.AbsoluteConstraints(323, 421, 55, 100));

        btnf4c7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnf4c7ActionPerformed(evt);
            }
        });
        add(btnf4c7, new org.netbeans.lib.awtextra.AbsoluteConstraints(384, 421, 55, 100));

        btnf4c8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnf4c8ActionPerformed(evt);
            }
        });
        add(btnf4c8, new org.netbeans.lib.awtextra.AbsoluteConstraints(445, 421, 55, 100));
    }// </editor-fold>//GEN-END:initComponents

    private void btnf1c1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnf1c1ActionPerformed
        controlador.seleccionarCarta(0, 0);
        actualizarTablero();
    }//GEN-LAST:event_btnf1c1ActionPerformed

    private void btnf1c2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnf1c2ActionPerformed
        controlador.seleccionarCarta(0, 1);
        actualizarTablero();
    }//GEN-LAST:event_btnf1c2ActionPerformed

    private void btnf1c3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnf1c3ActionPerformed
        controlador.seleccionarCarta(0, 2);
        actualizarTablero();
    }//GEN-LAST:event_btnf1c3ActionPerformed

    private void btnf1c4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnf1c4ActionPerformed
        controlador.seleccionarCarta(0, 3);
        actualizarTablero();
    }//GEN-LAST:event_btnf1c4ActionPerformed

    private void btnf1c5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnf1c5ActionPerformed
        controlador.seleccionarCarta(0, 4);
        actualizarTablero();
    }//GEN-LAST:event_btnf1c5ActionPerformed

    private void btnf1c6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnf1c6ActionPerformed
        controlador.seleccionarCarta(0, 5);
        actualizarTablero();
    }//GEN-LAST:event_btnf1c6ActionPerformed

    private void btnf1c7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnf1c7ActionPerformed
        controlador.seleccionarCarta(0, 6);
        actualizarTablero();
    }//GEN-LAST:event_btnf1c7ActionPerformed

    private void btnf1c8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnf1c8ActionPerformed
        controlador.seleccionarCarta(0, 7);
        actualizarTablero();
    }//GEN-LAST:event_btnf1c8ActionPerformed

    private void btnf2c1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnf2c1ActionPerformed
        controlador.seleccionarCarta(1, 0);
        actualizarTablero();
    }//GEN-LAST:event_btnf2c1ActionPerformed

    private void btnf2c2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnf2c2ActionPerformed
        controlador.seleccionarCarta(1, 1);
        actualizarTablero();
    }//GEN-LAST:event_btnf2c2ActionPerformed

    private void btnf2c3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnf2c3ActionPerformed
        controlador.seleccionarCarta(1, 2);
        actualizarTablero();
    }//GEN-LAST:event_btnf2c3ActionPerformed

    private void btnf2c4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnf2c4ActionPerformed
        controlador.seleccionarCarta(1, 3);
        actualizarTablero();
    }//GEN-LAST:event_btnf2c4ActionPerformed

    private void btnf2c5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnf2c5ActionPerformed
        controlador.seleccionarCarta(1, 4);
        actualizarTablero();
    }//GEN-LAST:event_btnf2c5ActionPerformed

    private void btnf2c6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnf2c6ActionPerformed
        controlador.seleccionarCarta(1, 5);
        actualizarTablero();
    }//GEN-LAST:event_btnf2c6ActionPerformed

    private void btnf2c7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnf2c7ActionPerformed
        controlador.seleccionarCarta(1, 6);
        actualizarTablero();
    }//GEN-LAST:event_btnf2c7ActionPerformed

    private void btnf2c8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnf2c8ActionPerformed
        controlador.seleccionarCarta(1, 7);
        actualizarTablero();
    }//GEN-LAST:event_btnf2c8ActionPerformed

    private void btnf3c1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnf3c1ActionPerformed
        controlador.seleccionarCarta(2, 0);
        actualizarTablero();
    }//GEN-LAST:event_btnf3c1ActionPerformed

    private void btnf3c2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnf3c2ActionPerformed
        controlador.seleccionarCarta(2, 1);
        actualizarTablero();
    }//GEN-LAST:event_btnf3c2ActionPerformed

    private void btnf3c3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnf3c3ActionPerformed
        controlador.seleccionarCarta(2, 2);
        actualizarTablero();
    }//GEN-LAST:event_btnf3c3ActionPerformed

    private void btnf3c4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnf3c4ActionPerformed
        controlador.seleccionarCarta(2, 3);
        actualizarTablero();
    }//GEN-LAST:event_btnf3c4ActionPerformed

    private void btnf3c5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnf3c5ActionPerformed
        controlador.seleccionarCarta(2, 4);
        actualizarTablero();
    }//GEN-LAST:event_btnf3c5ActionPerformed

    private void btnf3c6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnf3c6ActionPerformed
        controlador.seleccionarCarta(2, 5);
        actualizarTablero();
    }//GEN-LAST:event_btnf3c6ActionPerformed

    private void btnf3c7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnf3c7ActionPerformed
        controlador.seleccionarCarta(2, 6);
        actualizarTablero();
    }//GEN-LAST:event_btnf3c7ActionPerformed

    private void btnf3c8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnf3c8ActionPerformed
        controlador.seleccionarCarta(2, 7);
        actualizarTablero();
    }//GEN-LAST:event_btnf3c8ActionPerformed

    private void btnf4c1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnf4c1ActionPerformed
        controlador.seleccionarCarta(3, 0);
        actualizarTablero();
    }//GEN-LAST:event_btnf4c1ActionPerformed

    private void btnf4c2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnf4c2ActionPerformed
        controlador.seleccionarCarta(3, 1);
        actualizarTablero();
    }//GEN-LAST:event_btnf4c2ActionPerformed

    private void btnf4c3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnf4c3ActionPerformed
        controlador.seleccionarCarta(3, 2);
        actualizarTablero();
    }//GEN-LAST:event_btnf4c3ActionPerformed

    private void btnf4c4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnf4c4ActionPerformed
        controlador.seleccionarCarta(3, 3);
        actualizarTablero();
    }//GEN-LAST:event_btnf4c4ActionPerformed

    private void btnf4c5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnf4c5ActionPerformed
        controlador.seleccionarCarta(3, 4);
        actualizarTablero();
    }//GEN-LAST:event_btnf4c5ActionPerformed

    private void btnf4c6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnf4c6ActionPerformed
        controlador.seleccionarCarta(3, 5);
        actualizarTablero();
    }//GEN-LAST:event_btnf4c6ActionPerformed

    private void btnf4c7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnf4c7ActionPerformed
        controlador.seleccionarCarta(3, 6);
        actualizarTablero();
    }//GEN-LAST:event_btnf4c7ActionPerformed

    private void btnf4c8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnf4c8ActionPerformed
        controlador.seleccionarCarta(3, 7);
        actualizarTablero();
    }//GEN-LAST:event_btnf4c8ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnf1c1;
    private javax.swing.JButton btnf1c2;
    private javax.swing.JButton btnf1c3;
    private javax.swing.JButton btnf1c4;
    private javax.swing.JButton btnf1c5;
    private javax.swing.JButton btnf1c6;
    private javax.swing.JButton btnf1c7;
    private javax.swing.JButton btnf1c8;
    private javax.swing.JButton btnf2c1;
    private javax.swing.JButton btnf2c2;
    private javax.swing.JButton btnf2c3;
    private javax.swing.JButton btnf2c4;
    private javax.swing.JButton btnf2c5;
    private javax.swing.JButton btnf2c6;
    private javax.swing.JButton btnf2c7;
    private javax.swing.JButton btnf2c8;
    private javax.swing.JButton btnf3c1;
    private javax.swing.JButton btnf3c2;
    private javax.swing.JButton btnf3c3;
    private javax.swing.JButton btnf3c4;
    private javax.swing.JButton btnf3c5;
    private javax.swing.JButton btnf3c6;
    private javax.swing.JButton btnf3c7;
    private javax.swing.JButton btnf3c8;
    private javax.swing.JButton btnf4c1;
    private javax.swing.JButton btnf4c2;
    private javax.swing.JButton btnf4c3;
    private javax.swing.JButton btnf4c4;
    private javax.swing.JButton btnf4c5;
    private javax.swing.JButton btnf4c6;
    private javax.swing.JButton btnf4c7;
    private javax.swing.JButton btnf4c8;
    // End of variables declaration//GEN-END:variables
}
