/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package juegos;

/**
 *
 * @author andre
 */
public class jpnFacil extends javax.swing.JPanel {

    /**
     * Creates new form jpnFacil
     */
    
    public jpnFacil() {
        initComponents();
                
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnf1c2 = new javax.swing.JButton();
        btnf1c3 = new javax.swing.JButton();
        btnf1c4 = new javax.swing.JButton();
        btnf2c4 = new javax.swing.JButton();
        btnf2c2 = new javax.swing.JButton();
        btnf2c1 = new javax.swing.JButton();
        btnf2c3 = new javax.swing.JButton();
        btnf3c1 = new javax.swing.JButton();
        btnf3c2 = new javax.swing.JButton();
        btnf3c3 = new javax.swing.JButton();
        btnf3c4 = new javax.swing.JButton();
        btnf4c4 = new javax.swing.JButton();
        btnf4c3 = new javax.swing.JButton();
        btnf4c2 = new javax.swing.JButton();
        btnf4c1 = new javax.swing.JButton();
        btnf1c1 = new javax.swing.JButton();

        setPreferredSize(new java.awt.Dimension(900, 400));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnf1c2.addActionListener(this::btnf1c2ActionPerformed);
        add(btnf1c2, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 0, 60, 80));

        btnf1c3.addActionListener(this::btnf1c3ActionPerformed);
        add(btnf1c3, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 0, 60, 80));

        btnf1c4.addActionListener(this::btnf1c4ActionPerformed);
        add(btnf1c4, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 0, 60, 80));

        btnf2c4.addActionListener(this::btnf2c4ActionPerformed);
        add(btnf2c4, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 90, 60, 80));

        btnf2c2.addActionListener(this::btnf2c2ActionPerformed);
        add(btnf2c2, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 90, 60, 80));

        btnf2c1.addActionListener(this::btnf2c1ActionPerformed);
        add(btnf2c1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 90, 60, 80));

        btnf2c3.addActionListener(this::btnf2c3ActionPerformed);
        add(btnf2c3, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 90, 60, 80));

        btnf3c1.addActionListener(this::btnf3c1ActionPerformed);
        add(btnf3c1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 180, 60, 80));

        btnf3c2.addActionListener(this::btnf3c2ActionPerformed);
        add(btnf3c2, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 180, 60, 80));

        btnf3c3.addActionListener(this::btnf3c3ActionPerformed);
        add(btnf3c3, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 180, 60, 80));

        btnf3c4.addActionListener(this::btnf3c4ActionPerformed);
        add(btnf3c4, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 180, 60, 80));

        btnf4c4.addActionListener(this::btnf4c4ActionPerformed);
        add(btnf4c4, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 270, 60, 80));

        btnf4c3.addActionListener(this::btnf4c3ActionPerformed);
        add(btnf4c3, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 270, 60, 80));

        btnf4c2.addActionListener(this::btnf4c2ActionPerformed);
        add(btnf4c2, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 270, 60, 80));

        btnf4c1.addActionListener(this::btnf4c1ActionPerformed);
        add(btnf4c1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 270, 60, 80));

        btnf1c1.addActionListener(this::btnf1c1ActionPerformed);
        add(btnf1c1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 60, 80));
    }// </editor-fold>//GEN-END:initComponents

    private void btnf1c2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnf1c2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnf1c2ActionPerformed

    private void btnf1c3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnf1c3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnf1c3ActionPerformed

    private void btnf1c4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnf1c4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnf1c4ActionPerformed

    private void btnf2c4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnf2c4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnf2c4ActionPerformed

    private void btnf2c2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnf2c2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnf2c2ActionPerformed

    private void btnf2c1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnf2c1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnf2c1ActionPerformed

    private void btnf2c3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnf2c3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnf2c3ActionPerformed

    private void btnf3c1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnf3c1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnf3c1ActionPerformed

    private void btnf3c2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnf3c2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnf3c2ActionPerformed

    private void btnf3c3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnf3c3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnf3c3ActionPerformed

    private void btnf3c4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnf3c4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnf3c4ActionPerformed

    private void btnf4c4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnf4c4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnf4c4ActionPerformed

    private void btnf4c3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnf4c3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnf4c3ActionPerformed

    private void btnf4c2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnf4c2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnf4c2ActionPerformed

    private void btnf4c1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnf4c1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnf4c1ActionPerformed

    private void btnf1c1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnf1c1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnf1c1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnf1c1;
    private javax.swing.JButton btnf1c2;
    private javax.swing.JButton btnf1c3;
    private javax.swing.JButton btnf1c4;
    private javax.swing.JButton btnf2c1;
    private javax.swing.JButton btnf2c2;
    private javax.swing.JButton btnf2c3;
    private javax.swing.JButton btnf2c4;
    private javax.swing.JButton btnf3c1;
    private javax.swing.JButton btnf3c2;
    private javax.swing.JButton btnf3c3;
    private javax.swing.JButton btnf3c4;
    private javax.swing.JButton btnf4c1;
    private javax.swing.JButton btnf4c2;
    private javax.swing.JButton btnf4c3;
    private javax.swing.JButton btnf4c4;
    // End of variables declaration//GEN-END:variables
}
